- when building win32 DLL's use the -no-undefined flag.  Otherwise it   will only build static libraries.

diff --git a/bochs-testing/plugin-test/configure b/bochs-testing/plugin-test/configure
--- a/bochs-testing/plugin-test/configure
+++ b/bochs-testing/plugin-test/configure
@@ -6819,7 +6819,20 @@ LIBTOOL='$(SHELL) $(top_builddir)/libtool'
 
 subdirs="$subdirs libltdl"
 
+echo "$as_me:6822: checking if -no-undefined is required to build a shared library" >&5
+echo $ECHO_N "checking if -no-undefined is required to build a shared library... $ECHO_C" >&6
 LT_LDFLAGS=
+case $host in
+  *-*-cygwin* | *-*-mingw* | *-*-pw32* | *-*-os2*)
+    LT_LDFLAGS=-no-undefined
+    echo "$as_me:6828: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    ;;
+  *)
+    echo "$as_me:6832: result: no" >&5
+echo "${ECHO_T}no" >&6
+    ;;
+esac
 
 ac_config_files="$ac_config_files config.h Makefile test1-static/Makefile test2-dynamic/Makefile test3-twomodules/Makefile test4-interdep/Makefile test5-execsymbols/Makefile"
 cat >confcache <<\_ACEOF
@@ -6931,7 +6944,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:6934: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:6947: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -7098,7 +7111,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:7101: error: ambiguous option: $1
+    { { echo "$as_me:7114: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -7117,7 +7130,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:7120: error: unrecognized option: $1
+  -*) { { echo "$as_me:7133: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -7159,7 +7172,7 @@ do
   "test3-twomodules/Makefile" ) CONFIG_FILES="$CONFIG_FILES test3-twomodules/Makefile" ;;
   "test4-interdep/Makefile" ) CONFIG_FILES="$CONFIG_FILES test4-interdep/Makefile" ;;
   "test5-execsymbols/Makefile" ) CONFIG_FILES="$CONFIG_FILES test5-execsymbols/Makefile" ;;
-  *) { { echo "$as_me:7162: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:7175: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -7388,7 +7401,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:7391: creating $ac_file" >&5
+    { echo "$as_me:7404: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -7406,7 +7419,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:7409: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:7422: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -7419,7 +7432,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:7422: error: cannot find input file: $f" >&5
+           { { echo "$as_me:7435: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -7510,7 +7523,7 @@ if test "$no_recursion" != yes; then
     # parts of a large source tree are present.
     test -d $srcdir/$ac_subdir || continue
 
-    { echo "$as_me:7513: configuring in $ac_subdir" >&5
+    { echo "$as_me:7526: configuring in $ac_subdir" >&5
 echo "$as_me: configuring in $ac_subdir" >&6;}
     case $srcdir in
     .) ;;
@@ -7532,7 +7545,7 @@ done; }
 
        if test -d ./$ac_subdir; then :;
        else
-         { { echo "$as_me:7535: error: cannot create \`pwd\`/$ac_subdir" >&5
+         { { echo "$as_me:7548: error: cannot create \`pwd\`/$ac_subdir" >&5
 echo "$as_me: error: cannot create \`pwd\`/$ac_subdir" >&2;}
    { (exit 1); exit 1; }; }
        fi
@@ -7563,7 +7576,7 @@ echo "$as_me: error: cannot create \`pwd\`/$ac_subdir" >&2;}
     elif test -f $ac_sub_srcdir/configure.in; then
       ac_sub_configure=$ac_configure
     else
-      { echo "$as_me:7566: WARNING: no configuration information is in $ac_subdir" >&5
+      { echo "$as_me:7579: WARNING: no configuration information is in $ac_subdir" >&5
 echo "$as_me: WARNING: no configuration information is in $ac_subdir" >&2;}
       ac_sub_configure=
     fi
@@ -7577,12 +7590,12 @@ echo "$as_me: WARNING: no configuration information is in $ac_subdir" >&2;}
         ac_sub_cache_file=$ac_dots$cache_file ;;
       esac
 
-      { echo "$as_me:7580: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&5
+      { echo "$as_me:7593: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&5
 echo "$as_me: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&6;}
       # The eval makes quoting arguments work.
       eval $ac_sub_configure $ac_sub_configure_args \
            --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir ||
-        { { echo "$as_me:7585: error: $ac_sub_configure failed for $ac_subdir" >&5
+        { { echo "$as_me:7598: error: $ac_sub_configure failed for $ac_subdir" >&5
 echo "$as_me: error: $ac_sub_configure failed for $ac_subdir" >&2;}
    { (exit 1); exit 1; }; }
     fi
