- add test6-ltdlopen

diff --git a/bochs-testing/plugin-test/configure b/bochs-testing/plugin-test/configure
--- a/bochs-testing/plugin-test/configure
+++ b/bochs-testing/plugin-test/configure
@@ -6834,7 +6834,7 @@ echo "${ECHO_T}no" >&6
     ;;
 esac
 
-ac_config_files="$ac_config_files config.h Makefile test1-static/Makefile test2-dynamic/Makefile test3-twomodules/Makefile test4-interdep/Makefile test5-execsymbols/Makefile"
+ac_config_files="$ac_config_files config.h Makefile test1-static/Makefile test2-dynamic/Makefile test3-twomodules/Makefile test4-interdep/Makefile test5-execsymbols/Makefile test6-execsymbols2/Makefile"
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
 # tests run on this system so they can be shared between configure
@@ -7172,7 +7172,8 @@ do
   "test3-twomodules/Makefile" ) CONFIG_FILES="$CONFIG_FILES test3-twomodules/Makefile" ;;
   "test4-interdep/Makefile" ) CONFIG_FILES="$CONFIG_FILES test4-interdep/Makefile" ;;
   "test5-execsymbols/Makefile" ) CONFIG_FILES="$CONFIG_FILES test5-execsymbols/Makefile" ;;
-  *) { { echo "$as_me:7175: error: invalid argument: $ac_config_target" >&5
+  "test6-execsymbols2/Makefile" ) CONFIG_FILES="$CONFIG_FILES test6-execsymbols2/Makefile" ;;
+  *) { { echo "$as_me:7176: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -7401,7 +7402,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:7404: creating $ac_file" >&5
+    { echo "$as_me:7405: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -7419,7 +7420,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:7422: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:7423: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -7432,7 +7433,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:7435: error: cannot find input file: $f" >&5
+           { { echo "$as_me:7436: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -7523,7 +7524,7 @@ if test "$no_recursion" != yes; then
     # parts of a large source tree are present.
     test -d $srcdir/$ac_subdir || continue
 
-    { echo "$as_me:7526: configuring in $ac_subdir" >&5
+    { echo "$as_me:7527: configuring in $ac_subdir" >&5
 echo "$as_me: configuring in $ac_subdir" >&6;}
     case $srcdir in
     .) ;;
@@ -7545,7 +7546,7 @@ done; }
 
        if test -d ./$ac_subdir; then :;
        else
-         { { echo "$as_me:7548: error: cannot create \`pwd\`/$ac_subdir" >&5
+         { { echo "$as_me:7549: error: cannot create \`pwd\`/$ac_subdir" >&5
 echo "$as_me: error: cannot create \`pwd\`/$ac_subdir" >&2;}
    { (exit 1); exit 1; }; }
        fi
@@ -7576,7 +7577,7 @@ echo "$as_me: error: cannot create \`pwd\`/$ac_subdir" >&2;}
     elif test -f $ac_sub_srcdir/configure.in; then
       ac_sub_configure=$ac_configure
     else
-      { echo "$as_me:7579: WARNING: no configuration information is in $ac_subdir" >&5
+      { echo "$as_me:7580: WARNING: no configuration information is in $ac_subdir" >&5
 echo "$as_me: WARNING: no configuration information is in $ac_subdir" >&2;}
       ac_sub_configure=
     fi
@@ -7590,12 +7591,12 @@ echo "$as_me: WARNING: no configuration information is in $ac_subdir" >&2;}
         ac_sub_cache_file=$ac_dots$cache_file ;;
       esac
 
-      { echo "$as_me:7593: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&5
+      { echo "$as_me:7594: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&5
 echo "$as_me: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&6;}
       # The eval makes quoting arguments work.
       eval $ac_sub_configure $ac_sub_configure_args \
            --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir ||
-        { { echo "$as_me:7598: error: $ac_sub_configure failed for $ac_subdir" >&5
+        { { echo "$as_me:7599: error: $ac_sub_configure failed for $ac_subdir" >&5
 echo "$as_me: error: $ac_sub_configure failed for $ac_subdir" >&2;}
    { (exit 1); exit 1; }; }
     fi
