- select between libtool and win32 specific makefile targets

diff --git a/bochs-testing/plugin-test/configure b/bochs-testing/plugin-test/configure
--- a/bochs-testing/plugin-test/configure
+++ b/bochs-testing/plugin-test/configure
@@ -6833,6 +6833,20 @@ echo "${ECHO_T}yes" >&6
 echo "${ECHO_T}no" >&6
     ;;
 esac
+echo "$as_me:6836: checking how to build plugins" >&5
+echo $ECHO_N "checking how to build plugins... $ECHO_C" >&6
+case $host in
+  *-*-cygwin* | *-*-mingw* | *-*-pw32* | *-*-os2*)
+    PLUGIN_MAKEFILE_TARGET=all_win32_dlltool
+    echo "$as_me:6841: result: dlltool for cygwin/mingw" >&5
+echo "${ECHO_T}dlltool for cygwin/mingw" >&6
+    ;;
+  *)
+    PLUGIN_MAKEFILE_TARGET=all_libtool
+    echo "$as_me:6846: result: libtool" >&5
+echo "${ECHO_T}libtool" >&6
+    ;;
+esac
 
 ac_config_files="$ac_config_files config.h Makefile test1-static/Makefile test2-dynamic/Makefile test3-twomodules/Makefile test4-interdep/Makefile test5-execsymbols/Makefile test6-ltdlopen/Makefile test7-win32dll/Makefile"
 cat >confcache <<\_ACEOF
@@ -6944,7 +6958,7 @@ rm -f confdef2opt.sed
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:6947: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:6961: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -7111,7 +7125,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:7114: error: ambiguous option: $1
+    { { echo "$as_me:7128: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -7130,7 +7144,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:7133: error: unrecognized option: $1
+  -*) { { echo "$as_me:7147: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -7174,7 +7188,7 @@ do
   "test5-execsymbols/Makefile" ) CONFIG_FILES="$CONFIG_FILES test5-execsymbols/Makefile" ;;
   "test6-ltdlopen/Makefile" ) CONFIG_FILES="$CONFIG_FILES test6-ltdlopen/Makefile" ;;
   "test7-win32dll/Makefile" ) CONFIG_FILES="$CONFIG_FILES test7-win32dll/Makefile" ;;
-  *) { { echo "$as_me:7177: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:7191: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -7293,6 +7307,7 @@ s,@ac_ct_OBJDUMP@,$ac_ct_OBJDUMP,;t t
 s,@CPP@,$CPP,;t t
 s,@LIBTOOL@,$LIBTOOL,;t t
 s,@subdirs@,$subdirs,;t t
+s,@PLUGIN_MAKEFILE_TARGET@,$PLUGIN_MAKEFILE_TARGET,;t t
 s,@LT_LDFLAGS@,$LT_LDFLAGS,;t t
 CEOF
 
@@ -7403,7 +7418,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:7406: creating $ac_file" >&5
+    { echo "$as_me:7421: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -7421,7 +7436,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:7424: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:7439: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -7434,7 +7449,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:7437: error: cannot find input file: $f" >&5
+           { { echo "$as_me:7452: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -7525,7 +7540,7 @@ if test "$no_recursion" != yes; then
     # parts of a large source tree are present.
     test -d $srcdir/$ac_subdir || continue
 
-    { echo "$as_me:7528: configuring in $ac_subdir" >&5
+    { echo "$as_me:7543: configuring in $ac_subdir" >&5
 echo "$as_me: configuring in $ac_subdir" >&6;}
     case $srcdir in
     .) ;;
@@ -7547,7 +7562,7 @@ done; }
 
        if test -d ./$ac_subdir; then :;
        else
-         { { echo "$as_me:7550: error: cannot create \`pwd\`/$ac_subdir" >&5
+         { { echo "$as_me:7565: error: cannot create \`pwd\`/$ac_subdir" >&5
 echo "$as_me: error: cannot create \`pwd\`/$ac_subdir" >&2;}
    { (exit 1); exit 1; }; }
        fi
@@ -7578,7 +7593,7 @@ echo "$as_me: error: cannot create \`pwd\`/$ac_subdir" >&2;}
     elif test -f $ac_sub_srcdir/configure.in; then
       ac_sub_configure=$ac_configure
     else
-      { echo "$as_me:7581: WARNING: no configuration information is in $ac_subdir" >&5
+      { echo "$as_me:7596: WARNING: no configuration information is in $ac_subdir" >&5
 echo "$as_me: WARNING: no configuration information is in $ac_subdir" >&2;}
       ac_sub_configure=
     fi
@@ -7592,12 +7607,12 @@ echo "$as_me: WARNING: no configuration information is in $ac_subdir" >&2;}
         ac_sub_cache_file=$ac_dots$cache_file ;;
       esac
 
-      { echo "$as_me:7595: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&5
+      { echo "$as_me:7610: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&5
 echo "$as_me: running $ac_sub_configure $ac_sub_configure_args --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir" >&6;}
       # The eval makes quoting arguments work.
       eval $ac_sub_configure $ac_sub_configure_args \
            --cache-file=$ac_sub_cache_file --srcdir=$ac_sub_srcdir ||
-        { { echo "$as_me:7600: error: $ac_sub_configure failed for $ac_subdir" >&5
+        { { echo "$as_me:7615: error: $ac_sub_configure failed for $ac_subdir" >&5
 echo "$as_me: error: $ac_sub_configure failed for $ac_subdir" >&2;}
    { (exit 1); exit 1; }; }
     fi
