Added stub for the GTK version of the USB debugger. - For now showing a warning message box with "OK" and "Cancel" button. - Prepared SDL2 and X guis to use it. - Modified code to make sure win32 specific stuff is only present in win32usb.cc.

diff --git a/bochs/configure b/bochs/configure
--- a/bochs/configure
+++ b/bochs/configure
@@ -26034,7 +26034,7 @@ fi
   GUI_CXXFLAGS="$GUI_CXXFLAGS \$(X_CFLAGS)"
   GUI_LINK_OPTS="$GUI_LINK_OPTS \$(GUI_LINK_OPTS_X)"
   # The enhanced X debugger depends on GTK2
-  if test "$gui_debugger" = 1; then
+  if test "$gui_debugger" = 1 -o "$usb_debugger" = 1; then
     needs_gtk2=1
   fi
   use_gui_console=1
@@ -26060,8 +26060,10 @@ if test "$with_sdl" = yes; then
     NONPLUGIN_GUI_LINK_OPTS="`sdl-config --libs`"
   fi
   # The enhanced X debugger depends on GTK2
-  if test "$gui_debugger" = 1 -a "$DEFAULT_GUI" != win32; then
-    needs_gtk2=1
+  if test "$DEFAULT_GUI" != win32; then
+    if test "$gui_debugger" = 1 -o "$usb_debugger" = 1; then
+      needs_gtk2=1
+    fi
   fi
   if test "$with_win32" != yes -a "$with_wx" != yes; then
     case $target in
@@ -26096,8 +26098,10 @@ if test "$with_sdl2" = yes; then
     NONPLUGIN_GUI_LINK_OPTS="`sdl2-config --libs`"
   fi
   # The enhanced X debugger depends on GTK2
-  if test "$gui_debugger" = 1 -a "$DEFAULT_GUI" != win32; then
-    needs_gtk2=1
+  if test "$DEFAULT_GUI" != win32; then
+    if test "$gui_debugger" = 1 -o "$usb_debugger" = 1; then
+      needs_gtk2=1
+    fi
   fi
   if test "$with_win32" != yes -a "$with_wx" != yes; then
     case $target in
@@ -26329,8 +26333,10 @@ if test "$with_wx" = yes; then
       ;;
   esac
   # The enhanced X debugger depends on GTK2
-  if test "$gui_debugger" = 1 -a "$DEFAULT_GUI" != win32; then
-    needs_gtk2=1
+  if test "$DEFAULT_GUI" != win32; then
+    if test "$gui_debugger" = 1 -o "$usb_debugger" = 1; then
+      needs_gtk2=1
+    fi
   fi
 fi
 
@@ -26659,13 +26665,17 @@ fi
 
 USB_DBG_OBJS=""
 if test "$usb_debugger" = 1; then
-  if test "$DEFAULT_GUI" = win32 -o "$with_win32" = yes; then
+  if test "$bx_have_gtk_version" -ge 2; then
+    USB_DBG_OBJS="usb_debug.o gtk_usb_debug.o"
+    printf "%s\n" "#define BX_USB_DEBUGGER 1" >>confdefs.h
+
+  elif test "$DEFAULT_GUI" = win32 -o "$with_win32" = yes; then
     USB_DBG_OBJS="usb_debug.o win32usb.o"
     printf "%s\n" "#define BX_USB_DEBUGGER 1" >>confdefs.h
 
   else
-    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: The USB debugger supported only for Win32 cannot be compiled here, disabling it" >&5
-printf "%s\n" "$as_me: WARNING: The USB debugger supported only for Win32 cannot be compiled here, disabling it" >&2;}
+    { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: The USB debugger cannot be compiled here, disabling it" >&5
+printf "%s\n" "$as_me: WARNING: The USB debugger cannot be compiled here, disabling it" >&2;}
     printf "%s\n" "#define BX_USB_DEBUGGER 0" >>confdefs.h
 
   fi
