- I did AC_LANG_SAVE twice instead of SAVE...RESTORE - move number of processors before cpu level - move readline somewhere earlier - default cpu level=5 like bochs release - fpu support is off, like bochs release

diff --git a/bochs/configure.in b/bochs/configure.in
--- a/bochs/configure.in
+++ b/bochs/configure.in
@@ -50,44 +50,19 @@ AC_TRY_COMPILE([#include <hash_map.h>], [],
      AC_MSG_RESULT(yes)
      AC_DEFINE(HAVE_HASH_MAP)
    ], AC_MSG_RESULT(no))
-AC_LANG_SAVE
+AC_LANG_RESTORE
 
-AC_MSG_CHECKING(for cpu level)
-AC_ARG_ENABLE(cpu-level,
-  [  --enable-cpu-level                select cpu level (3,4,5,6)],
-  [case "$enableval" in
-     3)
-       AC_MSG_RESULT(3)
-       AC_DEFINE(BX_CPU_LEVEL, 3)
-       AC_DEFINE(BX_CPU_LEVEL_HACKED, 3)
-       ;;
-     4)
-       AC_MSG_RESULT(4)
-       AC_DEFINE(BX_CPU_LEVEL, 4)
-       AC_DEFINE(BX_CPU_LEVEL_HACKED, 4)
-       ;;
-     5)
-       AC_MSG_RESULT(5)
-       AC_DEFINE(BX_CPU_LEVEL, 5)
-       AC_DEFINE(BX_CPU_LEVEL_HACKED, 5)
-       ;;
-     6)
-       AC_MSG_RESULT(6)
-       AC_DEFINE(BX_CPU_LEVEL, 6)
-       AC_DEFINE(BX_CPU_LEVEL_HACKED, 6)
-       ;;
-     *)
-       echo " "
-       echo "ERROR: you must supply a valid CPU level to --enable-cpu-level"
-       exit 1
-       ;;
-   esac
-  ],
+AC_CHECK_LIB(readline, 
+  readline,
   [
-   AC_MSG_RESULT(6)
-   AC_DEFINE(BX_CPU_LEVEL, 6)
-   AC_DEFINE(BX_CPU_LEVEL_HACKED, 6)
+    AC_DEFINE(HAVE_LIBREADLINE, 1)
+    READLINE_LIB='-lreadline'
   ]
+)
+  AC_SUBST(READLINE_LIB)
+
+AC_CHECK_HEADER(readline/history.h,
+  AC_DEFINE(HAVE_READLINE_HISTORY_H)
   )
 
 AC_MSG_CHECKING(for number of processors)
@@ -120,11 +95,60 @@ AC_ARG_ENABLE(processors,
    bx_procs="$enableval"
   ],
   [
-   AC_MSG_RESULT(2)
-   AC_DEFINE(BX_SMP_PROCESSORS, 2)
-   AC_DEFINE(BX_BOOTSTRAP_PROCESSOR, 0)
-   AC_DEFINE(BX_IOAPIC_DEFAULT_ID, 2)
-   bx_procs=2
+     AC_MSG_RESULT(1)
+     AC_DEFINE(BX_SMP_PROCESSORS, 1)
+     AC_DEFINE(BX_BOOTSTRAP_PROCESSOR, 0)
+     AC_DEFINE(BX_IOAPIC_DEFAULT_ID, 1)
+     bx_procs=1
+  ]
+  )
+
+AC_MSG_CHECKING(for cpu level)
+AC_ARG_ENABLE(cpu-level,
+  [  --enable-cpu-level                select cpu level (3,4,5,6)],
+  [case "$enableval" in
+     3)
+       AC_MSG_RESULT(3)
+       AC_DEFINE(BX_CPU_LEVEL, 3)
+       AC_DEFINE(BX_CPU_LEVEL_HACKED, 3)
+       ;;
+     4)
+       AC_MSG_RESULT(4)
+       AC_DEFINE(BX_CPU_LEVEL, 4)
+       AC_DEFINE(BX_CPU_LEVEL_HACKED, 4)
+       ;;
+     5)
+       AC_MSG_RESULT(5)
+       AC_DEFINE(BX_CPU_LEVEL, 5)
+       AC_DEFINE(BX_CPU_LEVEL_HACKED, 5)
+       ;;
+     6)
+       AC_MSG_RESULT(6)
+       AC_DEFINE(BX_CPU_LEVEL, 6)
+       AC_DEFINE(BX_CPU_LEVEL_HACKED, 6)
+       ;;
+     *)
+       echo " "
+       echo "ERROR: you must supply a valid CPU level to --enable-cpu-level"
+       exit 1
+       ;;
+   esac
+   if test "$bx_procs" -gt 1 -a "$enableval" -lt 6; then
+     echo "ERROR: with >1 processor, use --enable-cpu-level=6"
+     exit 1
+   fi
+  ],
+  [
+    # for multiprocessors, cpu level must be 6
+    if test "$bx_procs" -gt 1; then
+      AC_MSG_RESULT(6)
+      AC_DEFINE(BX_CPU_LEVEL, 6)
+      AC_DEFINE(BX_CPU_LEVEL_HACKED, 6)
+    else
+      AC_MSG_RESULT(5)
+      AC_DEFINE(BX_CPU_LEVEL, 5)
+      AC_DEFINE(BX_CPU_LEVEL_HACKED, 5)
+    fi
   ]
   )
 
@@ -204,6 +228,7 @@ AC_ARG_ENABLE(apic,
    ],
   [
     if test "$bx_procs" -gt 1; then
+      # enable APIC by default, if processors>1
       AC_MSG_RESULT(yes)
       AC_DEFINE(BX_APIC_SUPPORT, 1)
       IOAPIC_OBJS='ioapic.o'
@@ -338,19 +363,6 @@ AC_ARG_ENABLE(debugger,
     ]
   )
 AC_SUBST(DEBUGGER_VAR)
-
-AC_CHECK_LIB(readline, 
-  readline,
-  [
-    AC_DEFINE(HAVE_LIBREADLINE, 1)
-    READLINE_LIB='-lreadline'
-  ]
-)
-  AC_SUBST(READLINE_LIB)
-
-AC_CHECK_HEADER(readline/history.h,
-  AC_DEFINE(HAVE_READLINE_HISTORY_H)
-  )
 
 AC_MSG_CHECKING(for disassembler support)
 AC_ARG_ENABLE(disasm,
@@ -513,12 +525,11 @@ AC_ARG_ENABLE(fpu,
     echo " "
     echo "ERROR: --enable-fpu does not accept a path"
     exit 1
-   fi],
+   fi
+   ],
   [
-    AC_MSG_RESULT(yes)
-    AC_DEFINE(BX_SUPPORT_FPU, 1)
-    FPU_VAR='$(FPU_LIB)'
-    FPU_GLUE_OBJ='$(FPU_GLUE_OBJ)'
+    AC_MSG_RESULT(no)
+    AC_DEFINE(BX_SUPPORT_FPU, 0)
     ]
   )
 AC_SUBST(FPU_VAR)
