cleanup configure options. All paging related stuff is now automatically set/unset according to cpu-level option. Related configure options (--enable-pae, --enable-mtrr, --enable-global-pages, --enable-large-pages) are deprecated. Less configure options - less configure problems :)

diff --git a/bochs/configure b/bochs/configure
--- a/bochs/configure
+++ b/bochs/configure
@@ -1562,11 +1562,7 @@ Optional Features:
   --enable-usb                      enable limited USB UHCI support
   --enable-usb-ohci                 enable limited USB OHCI support
   --enable-pnic                     enable PCI pseudo NIC support
-  --enable-large-pages              support for large pages (2M/4M pages)
-  --enable-pae                      support Physical Address Extensions
-  --enable-global-pages             support for global pages in PDE/PTE
   --enable-1g-pages                 support for 1G pages in long mode
-  --enable-mtrr                     support for MTRR/PAT registers
   --enable-repeat-speedups          support repeated IO and mem copy speedups
   --enable-trace-cache              support instruction trace cache
   --enable-fast-function-calls      support for fast function calls (gcc on x86 only)
@@ -1610,9 +1606,12 @@ Optional Features:
   --enable-iodebug                  enable I/O interface to debugger
   --enable-docbook                  build the Docbook documentation
   --enable-xpm                      enable the check for XPM support
+  --enable-pae                      enables PAE support (deprecated)
+  --enable-mtrr                     enables MTRR/PAT support (deprecated)
+  --enable-large-pages              enables PSE support (deprecated)
+  --enable-global-pages             enables Global Pages support (deprecated)
   --enable-guest2host-tlb           enables guest to host addr TLB for speed (deprecated)
   --enable-icache                   support instruction cache (deprecated)
-  --enable-external-debugger        enables external debugger interface (deprecated)
   --enable-port-e9-hack             writes to port e9 go to console (deprecated)
 
 Optional Packages:
@@ -4370,7 +4369,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4373 "configure"' > conftest.$ac_ext
+  echo '#line 4372 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -6572,11 +6571,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6575: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6574: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6579: \$? = $ac_status" >&5
+   echo "$as_me:6578: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6805,11 +6804,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6808: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6807: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:6812: \$? = $ac_status" >&5
+   echo "$as_me:6811: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -6872,11 +6871,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:6875: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:6874: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:6879: \$? = $ac_status" >&5
+   echo "$as_me:6878: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9001,7 +9000,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9004 "configure"
+#line 9003 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -9099,7 +9098,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9102 "configure"
+#line 9101 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11274,11 +11273,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11277: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11276: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:11281: \$? = $ac_status" >&5
+   echo "$as_me:11280: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -11341,11 +11340,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:11344: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:11343: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:11348: \$? = $ac_status" >&5
+   echo "$as_me:11347: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -12651,7 +12650,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12654 "configure"
+#line 12653 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12749,7 +12748,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 12752 "configure"
+#line 12751 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -13572,11 +13571,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13575: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13574: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:13579: \$? = $ac_status" >&5
+   echo "$as_me:13578: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -13639,11 +13638,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:13642: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:13641: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:13646: \$? = $ac_status" >&5
+   echo "$as_me:13645: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -15650,11 +15649,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15653: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15652: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15657: \$? = $ac_status" >&5
+   echo "$as_me:15656: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15883,11 +15882,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15886: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15885: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:15890: \$? = $ac_status" >&5
+   echo "$as_me:15889: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -15950,11 +15949,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:15953: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:15952: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:15957: \$? = $ac_status" >&5
+   echo "$as_me:15956: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -18079,7 +18078,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18082 "configure"
+#line 18081 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -18177,7 +18176,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 18180 "configure"
+#line 18179 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -20364,7 +20363,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 20367 "configure"
+#line 20366 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -34342,144 +34341,6 @@ fi
 
 
 
-
-{ echo "$as_me:$LINENO: checking for large pages support" >&5
-echo $ECHO_N "checking for large pages support... $ECHO_C" >&6; }
-# Check whether --enable-large-pages was given.
-if test "${enable_large_pages+set}" = set; then
-  enableval=$enable_large_pages; if test "$enableval" = yes; then
-    { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-    cat >>confdefs.h <<\_ACEOF
-#define BX_SUPPORT_LARGE_PAGES 1
-_ACEOF
-
-    support_large_pages=1
-   else
-    { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-    cat >>confdefs.h <<\_ACEOF
-#define BX_SUPPORT_LARGE_PAGES 0
-_ACEOF
-
-    support_large_pages=0
-   fi
-else
-
-    if test "$bx_cpu_level" -gt 4; then
-      { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-      cat >>confdefs.h <<\_ACEOF
-#define BX_SUPPORT_LARGE_PAGES 1
-_ACEOF
-
-      support_large_pages=1
-    else
-      { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-      cat >>confdefs.h <<\_ACEOF
-#define BX_SUPPORT_LARGE_PAGES 0
-_ACEOF
-
-      support_large_pages=0
-    fi
-
-
-fi
-
-
-
-{ echo "$as_me:$LINENO: checking for PAE support" >&5
-echo $ECHO_N "checking for PAE support... $ECHO_C" >&6; }
-# Check whether --enable-pae was given.
-if test "${enable_pae+set}" = set; then
-  enableval=$enable_pae; if test "$enableval" = yes; then
-    { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-    cat >>confdefs.h <<\_ACEOF
-#define BX_SUPPORT_PAE 1
-_ACEOF
-
-    support_pae=1
-   else
-    { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-    cat >>confdefs.h <<\_ACEOF
-#define BX_SUPPORT_PAE 0
-_ACEOF
-
-    support_pae=0
-   fi
-else
-
-    if test "$bx_cpu_level" -gt 5; then
-      { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-      cat >>confdefs.h <<\_ACEOF
-#define BX_SUPPORT_PAE 1
-_ACEOF
-
-      support_pae=1
-    else
-      { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-      cat >>confdefs.h <<\_ACEOF
-#define BX_SUPPORT_PAE 0
-_ACEOF
-
-      support_pae=0
-    fi
-
-
-fi
-
-
-{ echo "$as_me:$LINENO: checking for global pages support" >&5
-echo $ECHO_N "checking for global pages support... $ECHO_C" >&6; }
-# Check whether --enable-global-pages was given.
-if test "${enable_global_pages+set}" = set; then
-  enableval=$enable_global_pages; if test "$enableval" = yes; then
-    { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-    cat >>confdefs.h <<\_ACEOF
-#define BX_SUPPORT_GLOBAL_PAGES 1
-_ACEOF
-
-    support_global_pages=1
-   else
-    { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-    cat >>confdefs.h <<\_ACEOF
-#define BX_SUPPORT_GLOBAL_PAGES 0
-_ACEOF
-
-    support_global_pages=0
-   fi
-else
-
-    if test "$bx_cpu_level" -gt 5; then
-      # enable by default
-      { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-      cat >>confdefs.h <<\_ACEOF
-#define BX_SUPPORT_GLOBAL_PAGES 1
-_ACEOF
-
-      support_global_pages=1
-    else
-      { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-      cat >>confdefs.h <<\_ACEOF
-#define BX_SUPPORT_GLOBAL_PAGES 0
-_ACEOF
-
-      support_global_pages=0
-    fi
-
-
-fi
-
-
 { echo "$as_me:$LINENO: checking for long mode 1G pages support" >&5
 echo $ECHO_N "checking for long mode 1G pages support... $ECHO_C" >&6; }
 # Check whether --enable-1g-pages was given.
@@ -34520,66 +34381,6 @@ if test "$support_1g_pages" = 1 -a "$use_x86_64" = 0; then
 echo "$as_me: error: x86-64 mode is required for 1G pages support" >&2;}
    { (exit 1); exit 1; }; }
 fi
-
-if test "$bx_cpu_level" -lt 4 -a "$support_large_pages" = 1; then
-  { { echo "$as_me:$LINENO: error: for large paging support the CPU level must be >= 4" >&5
-echo "$as_me: error: for large paging support the CPU level must be >= 4" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-if test "$bx_cpu_level" -lt 5 -a "$support_pae" = 1; then
-  { { echo "$as_me:$LINENO: error: for PAE support the CPU level must be >= 5" >&5
-echo "$as_me: error: for PAE support the CPU level must be >= 5" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-if test "$bx_cpu_level" -lt 5 -a "$support_global_pages" = 1; then
-  { { echo "$as_me:$LINENO: error: for Global Pages support the CPU level must be >= 5" >&5
-echo "$as_me: error: for Global Pages support the CPU level must be >= 5" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-{ echo "$as_me:$LINENO: checking for MTRR/PAT support" >&5
-echo $ECHO_N "checking for MTRR/PAT support... $ECHO_C" >&6; }
-# Check whether --enable-mtrr was given.
-if test "${enable_mtrr+set}" = set; then
-  enableval=$enable_mtrr; if test "$enableval" = yes; then
-    { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-    cat >>confdefs.h <<\_ACEOF
-#define BX_SUPPORT_MTRR 1
-_ACEOF
-
-   else
-    { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-    cat >>confdefs.h <<\_ACEOF
-#define BX_SUPPORT_MTRR 0
-_ACEOF
-
-   fi
-else
-
-    if test "$bx_cpu_level" -gt 5; then
-      # enable by default
-      { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-      cat >>confdefs.h <<\_ACEOF
-#define BX_SUPPORT_MTRR 1
-_ACEOF
-
-    else
-      { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-      cat >>confdefs.h <<\_ACEOF
-#define BX_SUPPORT_MTRR 0
-_ACEOF
-
-    fi
-
-
-fi
-
 
 { echo "$as_me:$LINENO: checking for repeated IO and mem copy speedups" >&5
 echo $ECHO_N "checking for repeated IO and mem copy speedups... $ECHO_C" >&6; }
@@ -39322,6 +39123,78 @@ if test "$with_rfb" = yes -a "$cross_configure" = 0; then
 fi
 
 
+{ echo "$as_me:$LINENO: checking for PAE support (deprecated)" >&5
+echo $ECHO_N "checking for PAE support (deprecated)... $ECHO_C" >&6; }
+# Check whether --enable-pae was given.
+if test "${enable_pae+set}" = set; then
+  enableval=$enable_pae; { echo "$as_me:$LINENO: result: $enableval" >&5
+echo "${ECHO_T}$enableval" >&6; }
+   { { echo "$as_me:$LINENO: error: DEPRECATED - enabled automatically for CPU_LEVEL >= 6" >&5
+echo "$as_me: error: DEPRECATED - enabled automatically for CPU_LEVEL >= 6" >&2;}
+   { (exit 1); exit 1; }; }
+
+else
+
+   { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+fi
+
+
+{ echo "$as_me:$LINENO: checking for MTRR/PAR support (deprecated)" >&5
+echo $ECHO_N "checking for MTRR/PAR support (deprecated)... $ECHO_C" >&6; }
+# Check whether --enable-mtrr was given.
+if test "${enable_mtrr+set}" = set; then
+  enableval=$enable_mtrr; { echo "$as_me:$LINENO: result: $enableval" >&5
+echo "${ECHO_T}$enableval" >&6; }
+   { { echo "$as_me:$LINENO: error: DEPRECATED - enabled automatically for CPU_LEVEL >= 6" >&5
+echo "$as_me: error: DEPRECATED - enabled automatically for CPU_LEVEL >= 6" >&2;}
+   { (exit 1); exit 1; }; }
+
+else
+
+   { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+fi
+
+
+{ echo "$as_me:$LINENO: checking for LARGE PAGES (PSE) support (deprecated)" >&5
+echo $ECHO_N "checking for LARGE PAGES (PSE) support (deprecated)... $ECHO_C" >&6; }
+# Check whether --enable-large-pages was given.
+if test "${enable_large_pages+set}" = set; then
+  enableval=$enable_large_pages; { echo "$as_me:$LINENO: result: $enableval" >&5
+echo "${ECHO_T}$enableval" >&6; }
+   { { echo "$as_me:$LINENO: error: DEPRECATED - enabled automatically for CPU_LEVEL >= 5" >&5
+echo "$as_me: error: DEPRECATED - enabled automatically for CPU_LEVEL >= 5" >&2;}
+   { (exit 1); exit 1; }; }
+
+else
+
+   { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+fi
+
+
+{ echo "$as_me:$LINENO: checking for GLOBAL PAGES (PGE) support (deprecated)" >&5
+echo $ECHO_N "checking for GLOBAL PAGES (PGE) support (deprecated)... $ECHO_C" >&6; }
+# Check whether --enable-global-pages was given.
+if test "${enable_global_pages+set}" = set; then
+  enableval=$enable_global_pages; { echo "$as_me:$LINENO: result: $enableval" >&5
+echo "${ECHO_T}$enableval" >&6; }
+   { { echo "$as_me:$LINENO: error: DEPRECATED - enabled automatically for CPU_LEVEL >= 6" >&5
+echo "$as_me: error: DEPRECATED - enabled automatically for CPU_LEVEL >= 6" >&2;}
+   { (exit 1); exit 1; }; }
+
+else
+
+   { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+fi
+
+
 { echo "$as_me:$LINENO: checking for guest to host TLB support (deprecated)" >&5
 echo $ECHO_N "checking for guest to host TLB support (deprecated)... $ECHO_C" >&6; }
 # Check whether --enable-guest2host-tlb was given.
@@ -39348,24 +39221,6 @@ if test "${enable_icache+set}" = set; then
 echo "${ECHO_T}$enableval" >&6; }
    { { echo "$as_me:$LINENO: error: DEPRECATED - ALWAYS ON" >&5
 echo "$as_me: error: DEPRECATED - ALWAYS ON" >&2;}
-   { (exit 1); exit 1; }; }
-
-else
-
-   { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-
-fi
-
-
-{ echo "$as_me:$LINENO: checking for external debugger interface (deprecated)" >&5
-echo $ECHO_N "checking for external debugger interface (deprecated)... $ECHO_C" >&6; }
-# Check whether --enable-external-debugger was given.
-if test "${enable_external_debugger+set}" = set; then
-  enableval=$enable_external_debugger; { echo "$as_me:$LINENO: result: $enableval" >&5
-echo "${ECHO_T}$enableval" >&6; }
-   { { echo "$as_me:$LINENO: error: DEPRECATED - Peter Tattam's external debugger interface is not supported anymore" >&5
-echo "$as_me: error: DEPRECATED - Peter Tattam's external debugger interface is not supported anymore" >&2;}
    { (exit 1); exit 1; }; }
 
 else
