Integrate GTK GUI debugger frontend module

diff --git a/bochs/configure.in b/bochs/configure.in
--- a/bochs/configure.in
+++ b/bochs/configure.in
@@ -2,7 +2,7 @@ dnl // Process this file with autoconf to produce a configure script.
 
 AC_PREREQ(2.50)
 AC_INIT(bochs.h)
-AC_REVISION([[$Id: configure.in,v 1.383 2009-01-19 09:48:11 vruppert Exp $]])
+AC_REVISION([[$Id: configure.in,v 1.384 2009-01-31 10:04:25 sshwarts Exp $]])
 AC_CONFIG_HEADER(config.h)
 AC_CONFIG_HEADER(ltdlconf.h)
 
@@ -1260,17 +1260,21 @@ AC_ARG_ENABLE(debugger-gui,
   [if test "$enableval" = yes; then
     AC_MSG_RESULT(yes)
     AC_DEFINE(BX_DEBUGGER_GUI, 1)
+    gui_debugger=1
    else
     AC_MSG_RESULT(no)
     AC_DEFINE(BX_DEBUGGER_GUI, 0)
+    gui_debugger=0
    fi],
   [
     if test "$bx_debugger" = 1; then
       AC_MSG_RESULT(yes)
       AC_DEFINE(BX_DEBUGGER_GUI, 1)
+      gui_debugger=1
     else
       AC_MSG_RESULT(no)
       AC_DEFINE(BX_DEBUGGER_GUI, 0)
+      gui_debugger=0
     fi
     ]
   )
@@ -2297,7 +2301,7 @@ AC_MSG_RESULT($WX_CONFIG)
 
 ok_wx_version=0
 wx_multi_lib=0
-wx_needs_gtk2=0
+needs_gtk2=0
 AC_MSG_CHECKING(for wxWidgets library version)
 if test x$WX_CONFIG != xnot_found; then
   WX_VERSION=`$WX_CONFIG --version`
@@ -2313,7 +2317,7 @@ if test x$WX_CONFIG != xnot_found; then
       ok_wx_version=1
       wx_multi_lib=1
       case x$WX_BASENAME in
-	xwx_gtk2|xwx_gtk2u) wx_needs_gtk2=1 ;;
+	xwx_gtk2|xwx_gtk2u) needs_gtk2=1 ;;
 	*) ;;
       esac
       ;;
@@ -2358,6 +2362,10 @@ if test "$with_x11" = yes; then
   GUI_CFLAGS="$GUI_CFLAGS \$(X_CFLAGS)"
   GUI_CXXFLAGS="$GUI_CXXFLAGS \$(X_CFLAGS)"
   GUI_LINK_OPTS="$GUI_LINK_OPTS \$(GUI_LINK_OPTS_X)"
+  # The enhanced X debugger depends on GTK2
+  if test "$BX_DEBUGGER_GUI" = 1; then
+    needs_gtk2=1
+  fi
   check_xpm=0
   AC_MSG_CHECKING(whether user wants XPM support)
   AC_ARG_ENABLE(xpm,
@@ -2513,20 +2521,6 @@ if test "$with_wx" = yes; then
   else
     GUI_LINK_OPTS_WX="`$WX_CONFIG --libs`"
   fi
-  if test "$wx_needs_gtk2" = 1; then
-    PKG_CHECK_MODULES([GTK], [gtk+-2.0], [
-      WX_CFLAGS="$WX_CFLAGS $GTK_CFLAGS"
-      WX_CXXFLAGS="$WX_CXXFLAGS $GTK_CFLAGS"
-    ])
-  else
-    # if gtk-config exists, then add it to the cflags.
-    gtkconf=`gtk-config --cflags`
-    if test $? = 0; then
-      # gtk-config was found and returned 0, so it must return valid output
-      WX_CFLAGS="$WX_CFLAGS $gtkconf"
-      WX_CXXFLAGS="$WX_CXXFLAGS $gtkconf"
-    fi
-  fi
   # GUI_C*FLAGS are added to the compilation of every bochs file, not just
   # the files in gui/*.cc.  They are not used when building other things
   # such as bximage.
@@ -2557,6 +2551,22 @@ if test "$display_libs" = ""; then
   echo "individual display libraries, or --with-all-libs to detect the ones"
   echo "that Bochs supports."
   exit 1
+fi
+
+# some display libraries and the enhanced debugger may depend on the GTK+ software package
+if test "$needs_gtk2" = 1; then
+  # if pkg-config exists, then add it to the /gui cflags.
+  gtkconf=`pkg-config --cflags gtk+-2.0`
+  if test $? = 0; then
+    # pkg-config was found and returned 0, so it must return valid output
+    TOOLKIT_CXXFLAGS="$gtkconf"
+    LIBS="$LIBS `pkg-config --libs gtk+-2.0`"
+  else
+    echo "ERROR: pkg-config was not found, or unable to access the gtk+-2.0 package."
+    echo "Install pkg-config and the gtk+ development package,"
+    echo "or disable the gui debugger, or the wxWidgets display library (whichever is being used)."
+    exit 1
+  fi
 fi
 
 dnl To use wxWidgets you must select it as both the configuration interface
@@ -2591,6 +2601,7 @@ AC_SUBST(GUI_CXXFLAGS)
 AC_SUBST(WX_CONFIG)
 AC_SUBST(WX_CFLAGS)
 AC_SUBST(WX_CXXFLAGS)
+AC_SUBST(TOOLKIT_CXXFLAGS)
 
 AC_CHECK_PROGS(WGET, wget curl fetch, not_found)
 if test "$WGET" = not_found; then
@@ -2688,6 +2699,16 @@ case "$target" in
     ;;
 esac
 
+ENH_DBG_OBJS=""
+if test "$gui_debugger" = 1; then
+  if test "$with_win32" = yes; then
+     ENH_DBG_OBJS="win32_enh_dbg_osdep.o"
+  else
+     ENH_DBG_OBJS="gtk_enh_dbg_osdep.o"
+  fi
+fi
+AC_SUBST(ENH_DBG_OBJS)
+
 DIALOG_OBJS=""
 EXPORT_DYNAMIC="-export-dynamic"
 case $target in
@@ -2703,7 +2724,7 @@ case $target in
         LIBS="$LIBS -lcomctl32"
       fi
     fi
-    DIALOG_OBJS="win32dialog.o win32_enh_dbg_osdep.o"
+    DIALOG_OBJS="win32dialog.o"
     EXPORT_DYNAMIC=""
     ;;
 esac
