Fixed:
[ 725796 ] configure script bug

configure script bug
Current CVS configure script enables MMX even if FPU
is disabled.

diff --git a/bochs/configure b/bochs/configure
--- a/bochs/configure
+++ b/bochs/configure
@@ -1067,9 +1067,9 @@ Optional Features:
   --enable-num-sim=1 or 2           number of CPU simulators
   --enable-time0=n                  start at n instead of using time()
   --enable-vbe                      use VESA BIOS extensions
+  --enable-fpu                      compile in FPU emulation
   --enable-mmx                      MMX support
   --enable-3dnow                    3DNow! support
-  --enable-fpu                      compile in FPU emulation
   --enable-sse                      SSE/SSE2 support (--enable-sse=no|1|2)
   --enable-daz                      denormals-are-zeroes support
   --enable-sep                      SYSENTER/SYSEXIT support
@@ -1177,7 +1177,7 @@ ac_abs_top_srcdir=`cd "$ac_dir" && cd $ac_top_srcdir && pwd`
     else
       echo "$as_me: WARNING: no configuration information is in $ac_dir" >&2
     fi
-    cd "$ac_popdir"
+    cd $ac_popdir
   done
 fi
 
@@ -1374,7 +1374,7 @@ _ASBOX
       echo "$as_me: caught signal $ac_signal"
     echo "$as_me: exit $exit_status"
   } >&5
-  rm -f core *.core &&
+  rm -f core core.* *.core &&
   rm -rf conftest* confdefs* conf$$* $ac_clean_files &&
     exit $exit_status
      ' 0
@@ -2504,7 +2504,8 @@ if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   echo "$as_me:$LINENO: \$? = $ac_status" >&5
   (exit $ac_status); }; }; then
   for ac_declaration in \
-   '' \
+   ''\
+   '#include <stdlib.h>' \
    'extern "C" void std::exit (int) throw (); using std::exit;' \
    'extern "C" void std::exit (int); using std::exit;' \
    'extern "C" void exit (int) throw ();' \
@@ -2518,8 +2519,8 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-$ac_declaration
 #include <stdlib.h>
+$ac_declaration
 int
 main ()
 {
@@ -2829,7 +2830,8 @@ else
   fi
 fi
 for ac_declaration in \
-   '' \
+   ''\
+   '#include <stdlib.h>' \
    'extern "C" void std::exit (int) throw (); using std::exit;' \
    'extern "C" void std::exit (int); using std::exit;' \
    'extern "C" void exit (int) throw ();' \
@@ -2843,8 +2845,8 @@ _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-$ac_declaration
 #include <stdlib.h>
+$ac_declaration
 int
 main ()
 {
@@ -3526,7 +3528,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 3529 "configure"' > conftest.$ac_ext
+  echo '#line 3531 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -4059,7 +4061,7 @@ sed 's/^/| /' conftest.$ac_ext >&5
 ( exit $ac_status )
 ac_cv_header_stdc=no
 fi
-rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 fi
 fi
@@ -4601,7 +4603,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:4604:" \
+echo "$as_me:4606:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -5617,11 +5619,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:5620: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:5622: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:5624: \$? = $ac_status" >&5
+   echo "$as_me:5626: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -5850,11 +5852,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:5853: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:5855: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:5857: \$? = $ac_status" >&5
+   echo "$as_me:5859: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -5917,11 +5919,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:5920: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:5922: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:5924: \$? = $ac_status" >&5
+   echo "$as_me:5926: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -7977,7 +7979,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7980 "configure"
+#line 7982 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8075,7 +8077,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 8078 "configure"
+#line 8080 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10234,11 +10236,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10237: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10239: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:10241: \$? = $ac_status" >&5
+   echo "$as_me:10243: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -10301,11 +10303,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:10304: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:10306: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:10308: \$? = $ac_status" >&5
+   echo "$as_me:10310: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -11558,7 +11560,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11561 "configure"
+#line 11563 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -11656,7 +11658,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 11659 "configure"
+#line 11661 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12479,11 +12481,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12482: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12484: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12486: \$? = $ac_status" >&5
+   echo "$as_me:12488: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -12546,11 +12548,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12549: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12551: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12553: \$? = $ac_status" >&5
+   echo "$as_me:12555: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14540,11 +14542,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14543: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14545: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14547: \$? = $ac_status" >&5
+   echo "$as_me:14549: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -14773,11 +14775,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14776: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14778: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14780: \$? = $ac_status" >&5
+   echo "$as_me:14782: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings
@@ -14840,11 +14842,11 @@ else
    -e 's:.*FLAGS}? :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14843: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14845: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14847: \$? = $ac_status" >&5
+   echo "$as_me:14849: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16900,7 +16902,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 16903 "configure"
+#line 16905 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -16998,7 +17000,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 17001 "configure"
+#line 17003 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -19155,7 +19157,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 19158 "configure"
+#line 19160 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -21902,7 +21904,7 @@ sed 's/^/| /' conftest.$ac_ext >&5
 ( exit $ac_status )
 ac_cv_c_bigendian=yes
 fi
-rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 fi
 rm -f conftest.$ac_objext conftest.$ac_ext
@@ -22330,7 +22332,7 @@ echo "$as_me: error: cannot compute sizeof (unsigned char), 77
 See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; }
 fi
-rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 fi
 rm -f conftest.val
@@ -22691,7 +22693,7 @@ echo "$as_me: error: cannot compute sizeof (unsigned short), 77
 See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; }
 fi
-rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 fi
 rm -f conftest.val
@@ -23052,7 +23054,7 @@ echo "$as_me: error: cannot compute sizeof (unsigned int), 77
 See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; }
 fi
-rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 fi
 rm -f conftest.val
@@ -23413,7 +23415,7 @@ echo "$as_me: error: cannot compute sizeof (unsigned long), 77
 See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; }
 fi
-rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 fi
 rm -f conftest.val
@@ -23774,7 +23776,7 @@ echo "$as_me: error: cannot compute sizeof (unsigned long long), 77
 See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; }
 fi
-rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 fi
 rm -f conftest.val
@@ -24135,7 +24137,7 @@ echo "$as_me: error: cannot compute sizeof (int *), 77
 See \`config.log' for more details." >&2;}
    { (exit 1); exit 1; }; }
 fi
-rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
 fi
 rm -f conftest.val
@@ -32825,7 +32827,7 @@ sed 's/^/| /' conftest.$ac_ext >&5
 echo "${ECHO_T}no" >&6
 
 fi
-rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
     echo "$as_me:$LINENO: checking if readline works with -lcurses" >&5
 echo $ECHO_N "checking if readline works with -lcurses... $ECHO_C" >&6
@@ -32874,7 +32876,7 @@ sed 's/^/| /' conftest.$ac_ext >&5
 echo "${ECHO_T}no" >&6
 
 fi
-rm -f core *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+rm -f core core.* *.core gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
 fi
     LIBS=$OLD_LIBS
 
@@ -33218,6 +33220,53 @@ _ACEOF
 
 fi;
 
+support_fpu=1
+echo "$as_me:$LINENO: checking for FPU emulation" >&5
+echo $ECHO_N "checking for FPU emulation... $ECHO_C" >&6
+FPU_VAR=''
+FPU_GLUE_OBJ=''
+# Check whether --enable-fpu or --disable-fpu was given.
+if test "${enable_fpu+set}" = set; then
+  enableval="$enable_fpu"
+  if test "$enableval" = yes; then
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    cat >>confdefs.h <<\_ACEOF
+#define BX_SUPPORT_FPU 1
+_ACEOF
+
+    FPU_VAR='$(FPU_LIB)'
+    FPU_GLUE_OBJ='$(FPU_GLUE_OBJ)'
+   elif test "$enableval" = no; then
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+    cat >>confdefs.h <<\_ACEOF
+#define BX_SUPPORT_FPU 0
+_ACEOF
+
+    support_fpu=0
+   else
+    echo " "
+    echo "ERROR: --enable-fpu does not accept a path"
+    exit 1
+   fi
+
+else
+
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    cat >>confdefs.h <<\_ACEOF
+#define BX_SUPPORT_FPU 1
+_ACEOF
+
+    FPU_VAR='$(FPU_LIB)'
+    FPU_GLUE_OBJ='$(FPU_GLUE_OBJ)'
+
+
+fi;
+
+
+
 echo "$as_me:$LINENO: checking for MMX support" >&5
 echo $ECHO_N "checking for MMX support... $ECHO_C" >&6
 # Check whether --enable-mmx or --disable-mmx was given.
@@ -33241,12 +33290,14 @@ _ACEOF
 
 else
 
-    echo "$as_me:$LINENO: result: yes" >&5
+    if test "$support_fpu" = 1; then
+      echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-    cat >>confdefs.h <<\_ACEOF
+      cat >>confdefs.h <<\_ACEOF
 #define BX_SUPPORT_MMX 1
 _ACEOF
 
+    fi
 
 
 fi;
@@ -33292,51 +33343,6 @@ _ACEOF
 
 
 fi;
-
-echo "$as_me:$LINENO: checking for FPU emulation" >&5
-echo $ECHO_N "checking for FPU emulation... $ECHO_C" >&6
-FPU_VAR=''
-FPU_GLUE_OBJ=''
-# Check whether --enable-fpu or --disable-fpu was given.
-if test "${enable_fpu+set}" = set; then
-  enableval="$enable_fpu"
-  if test "$enableval" = yes; then
-    echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-    cat >>confdefs.h <<\_ACEOF
-#define BX_SUPPORT_FPU 1
-_ACEOF
-
-    FPU_VAR='$(FPU_LIB)'
-    FPU_GLUE_OBJ='$(FPU_GLUE_OBJ)'
-   elif test "$enableval" = no; then
-    echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-    cat >>confdefs.h <<\_ACEOF
-#define BX_SUPPORT_FPU 0
-_ACEOF
-
-   else
-    echo " "
-    echo "ERROR: --enable-fpu does not accept a path"
-    exit 1
-   fi
-
-else
-
-    echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-    cat >>confdefs.h <<\_ACEOF
-#define BX_SUPPORT_FPU 1
-_ACEOF
-
-    FPU_VAR='$(FPU_LIB)'
-    FPU_GLUE_OBJ='$(FPU_GLUE_OBJ)'
-
-
-fi;
-
-
 
 support_sse=0
 echo "$as_me:$LINENO: checking for SSE support" >&5
diff --git a/bochs/configure.in b/bochs/configure.in
--- a/bochs/configure.in
+++ b/bochs/configure.in
@@ -2,7 +2,7 @@ dnl // Process this file with autoconf to produce a configure script.
 
 AC_PREREQ(2.50)
 AC_INIT(bochs.h)
-AC_REVISION([[$Id: configure.in,v 1.233 2003-12-07 23:32:45 cbothamy Exp $]])
+AC_REVISION([[$Id: configure.in,v 1.234 2003-12-25 21:46:07 sshwarts Exp $]])
 AC_CONFIG_HEADER(config.h)
 AC_CONFIG_HEADER(ltdlconf.h)
 
@@ -1363,6 +1363,37 @@ AC_ARG_ENABLE(vbe,
     ]
   )
 
+support_fpu=1
+AC_MSG_CHECKING(for FPU emulation)
+FPU_VAR=''
+FPU_GLUE_OBJ=''
+AC_ARG_ENABLE(fpu,
+  [  --enable-fpu                      compile in FPU emulation],
+  [if test "$enableval" = yes; then
+    AC_MSG_RESULT(yes)
+    AC_DEFINE(BX_SUPPORT_FPU, 1)
+    FPU_VAR='$(FPU_LIB)'
+    FPU_GLUE_OBJ='$(FPU_GLUE_OBJ)'
+   elif test "$enableval" = no; then
+    AC_MSG_RESULT(no)
+    AC_DEFINE(BX_SUPPORT_FPU, 0)
+    support_fpu=0
+   else
+    echo " "
+    echo "ERROR: --enable-fpu does not accept a path"
+    exit 1
+   fi
+   ],
+  [
+    AC_MSG_RESULT(yes)
+    AC_DEFINE(BX_SUPPORT_FPU, 1)
+    FPU_VAR='$(FPU_LIB)'
+    FPU_GLUE_OBJ='$(FPU_GLUE_OBJ)'
+    ]
+  )
+AC_SUBST(FPU_VAR)
+AC_SUBST(FPU_GLUE_OBJ)
+
 AC_MSG_CHECKING(for MMX support)
 AC_ARG_ENABLE(mmx,
   [  --enable-mmx                      MMX support],
@@ -1375,8 +1406,10 @@ AC_ARG_ENABLE(mmx,
    fi
    ],
   [
-    AC_MSG_RESULT(yes)
-    AC_DEFINE(BX_SUPPORT_MMX, 1)
+    if test "$support_fpu" = 1; then
+      AC_MSG_RESULT(yes)
+      AC_DEFINE(BX_SUPPORT_MMX, 1)
+    fi
     ]
   )
 
@@ -1401,35 +1434,6 @@ AC_ARG_ENABLE(3dnow,
     fi
     ]
   )
-
-AC_MSG_CHECKING(for FPU emulation)
-FPU_VAR=''
-FPU_GLUE_OBJ=''
-AC_ARG_ENABLE(fpu,
-  [  --enable-fpu                      compile in FPU emulation],
-  [if test "$enableval" = yes; then
-    AC_MSG_RESULT(yes)
-    AC_DEFINE(BX_SUPPORT_FPU, 1)
-    FPU_VAR='$(FPU_LIB)'
-    FPU_GLUE_OBJ='$(FPU_GLUE_OBJ)'
-   elif test "$enableval" = no; then
-    AC_MSG_RESULT(no)
-    AC_DEFINE(BX_SUPPORT_FPU, 0)
-   else
-    echo " "
-    echo "ERROR: --enable-fpu does not accept a path"
-    exit 1
-   fi
-   ],
-  [
-    AC_MSG_RESULT(yes)
-    AC_DEFINE(BX_SUPPORT_FPU, 1)
-    FPU_VAR='$(FPU_LIB)'
-    FPU_GLUE_OBJ='$(FPU_GLUE_OBJ)'
-    ]
-  )
-AC_SUBST(FPU_VAR)
-AC_SUBST(FPU_GLUE_OBJ)
 
 support_sse=0
 AC_MSG_CHECKING(for SSE support)
