Check cpu level for paging features at configure stage

diff --git a/bochs/configure b/bochs/configure
--- a/bochs/configure
+++ b/bochs/configure
@@ -1048,11 +1048,11 @@ Optional Features:
   --enable-pnic                     enable PCI pseudo NIC support
   --enable-4meg-pages               support 4Megabyte pages extensions
   --enable-pae                      support Physical Address Extensions
+  --enable-global-pages             support for global pages in PDE/PTE
   --enable-guest2host-tlb           support guest to host addr TLB for speed
   --enable-repeat-speedups          support repeated IO and mem copy speedups
   --enable-icache                   support instruction cache
   --enable-fast-function-calls      support for fast function calls (gcc on x86 only)
-  --enable-global-pages             support for global pages in PDE/PTE
   --enable-host-specific-asms       support for host specific inline assembly
   --enable-ignore-bad-msr           ignore bad MSR references
   --enable-port-e9-hack             writes to port e9 go to console
@@ -34595,6 +34595,7 @@ echo "${ECHO_T}yes" >&6
 #define BX_SUPPORT_4MEG_PAGES 1
 _ACEOF
 
+    support_4M_pages=1
    else
     echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
@@ -34602,6 +34603,7 @@ echo "${ECHO_T}no" >&6
 #define BX_SUPPORT_4MEG_PAGES 0
 _ACEOF
 
+    support_4M_pages=0
    fi
 else
 
@@ -34612,6 +34614,7 @@ echo "${ECHO_T}yes" >&6
 #define BX_SUPPORT_4MEG_PAGES 1
 _ACEOF
 
+      support_4M_pages=1
     else
       echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
@@ -34619,6 +34622,7 @@ echo "${ECHO_T}no" >&6
 #define BX_SUPPORT_4MEG_PAGES 0
 _ACEOF
 
+      support_4M_pages=0
     fi
 
 
@@ -34637,6 +34641,7 @@ echo "${ECHO_T}yes" >&6
 #define BX_SupportPAE 1
 _ACEOF
 
+    support_pae=1
    else
     echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
@@ -34644,6 +34649,7 @@ echo "${ECHO_T}no" >&6
 #define BX_SupportPAE 0
 _ACEOF
 
+    support_pae=0
    fi
 else
 
@@ -34654,6 +34660,7 @@ echo "${ECHO_T}yes" >&6
 #define BX_SupportPAE 1
 _ACEOF
 
+      support_pae=1
     else
       echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
@@ -34661,11 +34668,75 @@ echo "${ECHO_T}no" >&6
 #define BX_SupportPAE 0
 _ACEOF
 
+      support_pae=0
     fi
 
 
 fi;
 
+echo "$as_me:$LINENO: checking for global pages support" >&5
+echo $ECHO_N "checking for global pages support... $ECHO_C" >&6
+# Check whether --enable-global-pages or --disable-global-pages was given.
+if test "${enable_global_pages+set}" = set; then
+  enableval="$enable_global_pages"
+  if test "$enableval" = yes; then
+    echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+    cat >>confdefs.h <<\_ACEOF
+#define BX_SupportGlobalPages 1
+_ACEOF
+
+    support_global_pages=1
+   else
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+    cat >>confdefs.h <<\_ACEOF
+#define BX_SupportGlobalPages 0
+_ACEOF
+
+    support_global_pages=0
+   fi
+else
+
+    if test "$bx_cpu_level" -gt 5; then
+      # enable by default
+      echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+      cat >>confdefs.h <<\_ACEOF
+#define BX_SupportGlobalPages 1
+_ACEOF
+
+      support_global_pages=1
+    else
+      echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+      cat >>confdefs.h <<\_ACEOF
+#define BX_SupportGlobalPages 0
+_ACEOF
+
+      support_global_pages=0
+    fi
+
+
+fi;
+
+if test "$bx_cpu_level" -lt 4 -a "$support_4M_pages" = 1; then
+  { { echo "$as_me:$LINENO: error: for 4M paging support the CPU level must be >= 4" >&5
+echo "$as_me: error: for 4M paging support the CPU level must be >= 4" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test "$bx_cpu_level" -lt 5 -a "$support_pae" = 1; then
+  { { echo "$as_me:$LINENO: error: for PAE support the CPU level must be >= 5" >&5
+echo "$as_me: error: for PAE support the CPU level must be >= 5" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+if test "$bx_cpu_level" -lt 5 -a "$support_global_pages" = 1; then
+  { { echo "$as_me:$LINENO: error: for Global Pages support the CPU level must be >= 5" >&5
+echo "$as_me: error: for Global Pages support the CPU level must be >= 5" >&2;}
+   { (exit 1); exit 1; }; }
+fi
 
 echo "$as_me:$LINENO: checking for guest to host TLB support" >&5
 echo $ECHO_N "checking for guest to host TLB support... $ECHO_C" >&6
@@ -34755,48 +34826,6 @@ else
     echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
     speedup_fastcall=0
-
-
-fi;
-
-echo "$as_me:$LINENO: checking for global pages support" >&5
-echo $ECHO_N "checking for global pages support... $ECHO_C" >&6
-# Check whether --enable-global-pages or --disable-global-pages was given.
-if test "${enable_global_pages+set}" = set; then
-  enableval="$enable_global_pages"
-  if test "$enableval" = yes; then
-    echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-    cat >>confdefs.h <<\_ACEOF
-#define BX_SupportGlobalPages 1
-_ACEOF
-
-   else
-    echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-    cat >>confdefs.h <<\_ACEOF
-#define BX_SupportGlobalPages 0
-_ACEOF
-
-   fi
-else
-
-    if test "$bx_cpu_level" -gt 5; then
-      # enable by default
-      echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-      cat >>confdefs.h <<\_ACEOF
-#define BX_SupportGlobalPages 1
-_ACEOF
-
-    else
-      echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-      cat >>confdefs.h <<\_ACEOF
-#define BX_SupportGlobalPages 0
-_ACEOF
-
-    fi
 
 
 fi;
