- rfb gui needs the socket function. on solaris, you need to link with   -lsocket to get it.

diff --git a/bochs/configure.in b/bochs/configure.in
--- a/bochs/configure.in
+++ b/bochs/configure.in
@@ -2,7 +2,7 @@ dnl // Process this file with autoconf to produce a configure script.
 
 AC_PREREQ(2.5)
 AC_INIT(bochs.h)
-AC_REVISION([[$Id: configure.in,v 1.129 2002-09-25 04:24:46 bdenney Exp $]])
+AC_REVISION([[$Id: configure.in,v 1.130 2002-09-26 01:45:10 bdenney Exp $]])
 AC_CONFIG_HEADER(config.h)
 
 dnl // Put Bochs version information right here so that it gets substituted
@@ -1486,6 +1486,18 @@ if test "$use_curses" = yes; then
   fi
 fi
 
+if test "$with_rfb" = yes -a "$cross_configure" = 0; then
+  # we need the socket function. if cross configuring, don't bother.
+  AC_CHECK_FUNCS(socket, have_socket=yes)
+  if test "$have_socket" != yes; then
+    AC_CHECK_LIB(socket, socket, 
+      [ GUI_LINK_OPTS_RFB="$GUI_LINK_OPTS_RFB -lsocket" ], 
+      [
+        echo 'ERROR: socket function required for RFB compile'
+        exit 1
+      ])
+  fi
+fi
 
 # The ACX_PTHREAD function was written by 
 # Steven G. Johnson <stevenj@alum.mit.edu> and 
