- commit TUN/TAP patch, though I can't really test it.  I can verify that if   you don't have if_tun.h the configure script does not enable TUN/TAP.

diff --git a/bochs/configure b/bochs/configure
--- a/bochs/configure
+++ b/bochs/configure
@@ -8664,6 +8664,54 @@ _ACEOF
 fi
 
 
+    echo "$as_me:$LINENO: checking for linux/if_tun.h" >&5
+echo $ECHO_N "checking for linux/if_tun.h... $ECHO_C" >&6
+if test "${ac_cv_header_linux_if_tun_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+	#include <asm/types.h>
+	#include <sys/socket.h>
+
+
+#include <linux/if_tun.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_header_linux_if_tun_h=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_header_linux_if_tun_h=no
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_linux_if_tun_h" >&5
+echo "${ECHO_T}$ac_cv_header_linux_if_tun_h" >&6
+if test $ac_cv_header_linux_if_tun_h = yes; then
+
+        NE2K_OBJS="$NE2K_OBJS eth_tuntap.o"
+        cat >>confdefs.h <<\_ACEOF
+#define HAVE_TUNTAP 1
+_ACEOF
+
+
+fi
+
+
     if test "$with_win32" = yes; then
       NE2K_OBJS="$NE2K_OBJS eth_win32.o"
     fi
