Move MMX to be runtime option

diff --git a/bochs/configure.in b/bochs/configure.in
--- a/bochs/configure.in
+++ b/bochs/configure.in
@@ -2,7 +2,7 @@ dnl // Process this file with autoconf to produce a configure script.
 
 AC_PREREQ(2.50)
 AC_INIT(bochs.h)
-AC_REVISION([[$Id: configure.in,v 1.428 2010-02-28 14:52:16 sshwarts Exp $]])
+AC_REVISION([[$Id: configure.in,v 1.429 2010-03-01 18:53:53 sshwarts Exp $]])
 AC_CONFIG_HEADER(config.h)
 AC_CONFIG_HEADER(ltdlconf.h)
 
@@ -576,6 +576,10 @@ AC_ARG_ENABLE(cpu-level,
    bx_cpu_level=$enableval
    if test "$use_smp" = 1 -a "$enableval" -lt 6; then
      echo "ERROR: with >1 processor, use --enable-cpu-level=6"
+     exit 1
+   fi
+   if test "$use_x86_64" = 1 -a "$enableval" -lt 6; then
+     echo "ERROR: --enable-cpu-level=6 required for x86-64 emulation"
      exit 1
    fi
   ],
@@ -1406,28 +1410,6 @@ AC_ARG_ENABLE(vmx,
 if test "$support_vmx" -lt 0 -a "$bx_cpu_level" -lt 6; then
   AC_MSG_ERROR([for VMX support the CPU level must be set to 6])
 fi
-
-AC_MSG_CHECKING(for MMX support)
-AC_ARG_ENABLE(mmx,
-  [  --enable-mmx                      MMX support],
-  [if test "$enableval" = yes; then
-    AC_MSG_RESULT(yes)
-    AC_DEFINE(BX_SUPPORT_MMX, 1)
-   elif test "$enableval" = no; then
-    AC_MSG_RESULT(no)
-    AC_DEFINE(BX_SUPPORT_MMX, 0)
-   fi
-   ],
-  [
-    if test "$bx_cpu_level" -ge 5; then
-      AC_MSG_RESULT(yes)
-      AC_DEFINE(BX_SUPPORT_MMX, 1)
-    else
-      AC_MSG_RESULT(no)
-      AC_DEFINE(BX_SUPPORT_MMX, 0)
-    fi
-    ]
-  )
 
 AC_MSG_CHECKING(for 3DNow! support)
 AC_ARG_ENABLE(3dnow,
