- try to improve the readline test.  Now I never use the readline test   generated by autoconf.  Instead I'm using AC_TRY_RUN to actually call   a readline function before assuming that things are ok.

diff --git a/bochs/configure b/bochs/configure
--- a/bochs/configure
+++ b/bochs/configure
@@ -42,7 +42,7 @@ ac_help="$ac_help
 ac_help="$ac_help
   --enable-disasm                   compile in support for disassembler"
 ac_help="$ac_help
- --enable-readline                  use readline library with debugger"
+ --enable-readline                  use readline library, if available"
 ac_help="$ac_help
   --enable-loader                   support calling external loader from debugger"
 ac_help="$ac_help
@@ -3641,8 +3641,86 @@ fi
 
 
 
-echo $ac_n "checking whether to use readline""... $ac_c" 1>&6
-echo "configure:3646: checking whether to use readline" >&5
+READLINE_LIB=""
+rl_without_curses_ok=no
+rl_with_curses_ok=no
+
+echo $ac_n "checking if readline works without -lcurses""... $ac_c" 1>&6
+echo "configure:3650: checking if readline works without -lcurses" >&5
+OLD_LIBS=$LIBS
+LIBS="$LIBS -lreadline"
+if test "$cross_compiling" = yes; then
+    { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
+else
+  cat > conftest.$ac_ext <<EOF
+#line 3657 "configure"
+#include "confdefs.h"
+
+  #include <stdio.h>
+  #include <readline/readline.h>
+  int main() { rl_initialize(); exit(0); }
+  
+EOF
+if { (eval echo configure:3665: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+then
+   echo "$ac_t""yes" 1>&6
+    rl_without_curses_ok=yes 
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -fr conftest*
+   echo "$ac_t""no" 1>&6 
+
+fi
+rm -fr conftest*
+fi
+
+echo $ac_n "checking if readline works with -lcurses""... $ac_c" 1>&6
+echo "configure:3680: checking if readline works with -lcurses" >&5
+LIBS="$LIBS -lcurses"
+if test "$cross_compiling" = yes; then
+    { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
+else
+  cat > conftest.$ac_ext <<EOF
+#line 3686 "configure"
+#include "confdefs.h"
+
+  #include <stdio.h>
+  #include <readline/readline.h>
+  int main() { rl_initialize(); exit(0); }
+  
+EOF
+if { (eval echo configure:3694: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+then
+  echo "$ac_t""yes" 1>&6
+   rl_with_curses_ok=yes 
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -fr conftest*
+   echo "$ac_t""no" 1>&6 
+
+fi
+rm -fr conftest*
+fi
+
+LIBS=$OLD_LIBS
+if test "$rl_without_curses_ok" = no -a "$rl_with_curses_ok" = no; then
+  echo WARNING: readline was found but it is broken, with or without the -lcurses link option
+  exit 1
+elif test "$rl_without_curses_ok" = no; then
+  # we must add -lcurses!
+  if test "$READLINE_LIB" != ""; then
+    echo Adding -lcurses to your library list.
+    READLINE_LIB="$READLINE_LIB -lcurses"
+  fi
+else
+  true # it worked without anything special
+fi
+
+
+echo $ac_n "checking whether user wants readline""... $ac_c" 1>&6
+echo "configure:3724: checking whether user wants readline" >&5
 # Check whether --enable-readline or --disable-readline was given.
 if test "${enable_readline+set}" = set; then
   enableval="$enable_readline"
@@ -3654,159 +3732,58 @@ if test "${enable_readline+set}" = set; then
      want_readline=no
    fi
 else
-   # default is yes
+  
     echo "$ac_t""yes" 1>&6
-    want_readline=yes 
+    want_readline=yes
+    
  
 fi
 
 
-
+echo $ac_n "checking whether to use readline""... $ac_c" 1>&6
+echo "configure:3745: checking whether to use readline" >&5
 if test "$want_readline" = yes; then
-  echo $ac_n "checking for readline in -lreadline""... $ac_c" 1>&6
-echo "configure:3668: checking for readline in -lreadline" >&5
-ac_lib_var=`echo readline'_'readline | sed 'y%./+-%__p_%'`
-if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
-  echo $ac_n "(cached) $ac_c" 1>&6
-else
-  ac_save_LIBS="$LIBS"
-LIBS="-lreadline  $LIBS"
-cat > conftest.$ac_ext <<EOF
-#line 3676 "configure"
-#include "confdefs.h"
-/* Override any gcc2 internal prototype to avoid an error.  */
-/* We use char because int might match the return type of a gcc2
-    builtin and then its argument prototype would still apply.  */
-char readline();
-
-int main() {
-readline()
-; return 0; }
-EOF
-if { (eval echo configure:3687: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
-  rm -rf conftest*
-  eval "ac_cv_lib_$ac_lib_var=yes"
-else
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  rm -rf conftest*
-  eval "ac_cv_lib_$ac_lib_var=no"
-fi
-rm -f conftest*
-LIBS="$ac_save_LIBS"
-
-fi
-if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
-  echo "$ac_t""yes" 1>&6
-  
-      if test "$bx_debugger" = 1; then
-	# only add readline library if debugger is on
-	cat >> confdefs.h <<\EOF
+  if test "$bx_debugger" = 1; then
+    if test "$rl_without_curses_ok" = yes; then
+      echo "$ac_t""yes" 1>&6
+      cat >> confdefs.h <<\EOF
 #define HAVE_LIBREADLINE 1
 EOF
 
-	READLINE_LIB='-lreadline'
-      fi
-    
-  
+      READLINE_LIB="-lreadline"
+    elif test "$rl_with_curses_ok" = yes; then
+      echo "$ac_t""yes" 1>&6
+      cat >> confdefs.h <<\EOF
+#define HAVE_LIBREADLINE 1
+EOF
+
+      READLINE_LIB="-lreadline -lcurses"
+      echo Adding -lcurses since readline requires it.
+    else
+      echo "$ac_t""no" 1>&6
+      echo WARNING: The readline library was found, but it is broken, with 
+      echo or without the -lcurses link option.
+    fi
+  else
+    echo "$ac_t""no" 1>&6
+  fi
 else
   echo "$ac_t""no" 1>&6
 fi
 
-  echo $ac_n "checking if readline works without -lcurses""... $ac_c" 1>&6
-echo "configure:3718: checking if readline works without -lcurses" >&5
-  OLD_LIBS=$LIBS
-  LIBS="$LIBS -lreadline"
-  rl_without_curses_ok=yes
-  if test "$cross_compiling" = yes; then
-    { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
-else
-  cat > conftest.$ac_ext <<EOF
-#line 3726 "configure"
-#include "confdefs.h"
-
-    #include <stdio.h>
-    #include <readline/readline.h>
-    int main() { rl_initialize(); exit(0); }
-    
-EOF
-if { (eval echo configure:3734: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
-then
-   echo "$ac_t""yes" 1>&6 
-else
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  rm -fr conftest*
-   
-      echo "$ac_t""no" 1>&6
-      rl_without_curses_ok=no
-    
-  
-fi
-rm -fr conftest*
-fi
-
-  echo $ac_n "checking if readline works with -lcurses""... $ac_c" 1>&6
-echo "configure:3751: checking if readline works with -lcurses" >&5
-  LIBS="$LIBS -lcurses"
-  rl_with_curses_ok=yes
-  if test "$cross_compiling" = yes; then
-    { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
-else
-  cat > conftest.$ac_ext <<EOF
-#line 3758 "configure"
-#include "confdefs.h"
-
-    #include <stdio.h>
-    #include <readline/readline.h>
-    int main() { rl_initialize(); exit(0); }
-    
-EOF
-if { (eval echo configure:3766: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
-then
-  echo "$ac_t""yes" 1>&6
-else
-  echo "configure: failed program was:" >&5
-  cat conftest.$ac_ext >&5
-  rm -fr conftest*
-  
-      echo "$ac_t""no" 1>&6
-      rl_with_curses_ok=no
-    
-  
-fi
-rm -fr conftest*
-fi
-
-  LIBS=$OLD_LIBS
-  if test "$rl_without_curses_ok" = no -a "$rl_with_curses_ok" = no; then
-    echo WARNING: readline enabled but it is broken, with or without the -lcurses link option
-    #exit 1
-  elif test "$rl_without_curses_ok" = no; then
-    # we must add -lcurses!
-    if test "$READLINE_LIB" != ""; then
-      echo Adding -lcurses to your library list.
-      READLINE_LIB="$READLINE_LIB -lcurses"
-    fi
-  else
-    true # it worked without anything special
-  fi
-fi
-  
-
 ac_safe=`echo "readline/history.h" | sed 'y%./+-%__p_%'`
 echo $ac_n "checking for readline/history.h""... $ac_c" 1>&6
-echo "configure:3800: checking for readline/history.h" >&5
+echo "configure:3777: checking for readline/history.h" >&5
 if eval "test \"`echo '$''{'ac_cv_header_$ac_safe'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
   cat > conftest.$ac_ext <<EOF
-#line 3805 "configure"
+#line 3782 "configure"
 #include "confdefs.h"
 #include <readline/history.h>
 EOF
 ac_try="$ac_cpp conftest.$ac_ext >/dev/null 2>conftest.out"
-{ (eval echo configure:3810: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
+{ (eval echo configure:3787: \"$ac_try\") 1>&5; (eval $ac_try) 2>&5; }
 ac_err=`grep -v '^ *+' conftest.out | grep -v "^conftest.${ac_ext}\$"`
 if test -z "$ac_err"; then
   rm -rf conftest*
@@ -3833,7 +3810,7 @@ fi
 
 
 echo $ac_n "checking for loader support""... $ac_c" 1>&6
-echo "configure:3837: checking for loader support" >&5
+echo "configure:3814: checking for loader support" >&5
 # Check whether --enable-loader or --disable-loader was given.
 if test "${enable_loader+set}" = set; then
   enableval="$enable_loader"
@@ -3871,7 +3848,7 @@ fi
 INSTRUMENT_DIR='instrument/stubs'
 
 echo $ac_n "checking for instrumentation support""... $ac_c" 1>&6
-echo "configure:3875: checking for instrumentation support" >&5
+echo "configure:3852: checking for instrumentation support" >&5
 # Check whether --enable-instrumentation or --disable-instrumentation was given.
 if test "${enable_instrumentation+set}" = set; then
   enableval="$enable_instrumentation"
@@ -4006,7 +3983,7 @@ fi
 
 
 echo $ac_n "checking for VGA emulation""... $ac_c" 1>&6
-echo "configure:4010: checking for VGA emulation" >&5
+echo "configure:3987: checking for VGA emulation" >&5
 # Check whether --enable-vga or --disable-vga was given.
 if test "${enable_vga+set}" = set; then
   enableval="$enable_vga"
@@ -4040,7 +4017,7 @@ fi
 
 
 echo $ac_n "checking for FPU emulation""... $ac_c" 1>&6
-echo "configure:4044: checking for FPU emulation" >&5
+echo "configure:4021: checking for FPU emulation" >&5
 FPU_VAR=''
 FPU_GLUE_OBJ=''
 # Check whether --enable-fpu or --disable-fpu was given.
@@ -4085,7 +4062,7 @@ fi
 
 
 echo $ac_n "checking for x86 debugger support""... $ac_c" 1>&6
-echo "configure:4089: checking for x86 debugger support" >&5
+echo "configure:4066: checking for x86 debugger support" >&5
 # Check whether --enable-x86-debugger or --disable-x86-debugger was given.
 if test "${enable_x86_debugger+set}" = set; then
   enableval="$enable_x86_debugger"
@@ -4121,7 +4098,7 @@ fi
 
 
 echo $ac_n "checking for CDROM support""... $ac_c" 1>&6
-echo "configure:4125: checking for CDROM support" >&5
+echo "configure:4102: checking for CDROM support" >&5
 # Check whether --enable-cdrom or --disable-cdrom was given.
 if test "${enable_cdrom+set}" = set; then
   enableval="$enable_cdrom"
@@ -4160,7 +4137,7 @@ fi
 
 
 echo $ac_n "checking for Sound Blaster 16 support""... $ac_c" 1>&6
-echo "configure:4164: checking for Sound Blaster 16 support" >&5
+echo "configure:4141: checking for Sound Blaster 16 support" >&5
 # Check whether --enable-sb16 or --disable-sb16 was given.
 if test "${enable_sb16+set}" = set; then
   enableval="$enable_sb16"
@@ -4234,7 +4211,7 @@ fi
 
 
 echo $ac_n "checking for I/O Interface to the debugger""... $ac_c" 1>&6
-echo "configure:4238: checking for I/O Interface to the debugger" >&5
+echo "configure:4215: checking for I/O Interface to the debugger" >&5
 IODEBUG_OBJS=''
 # Check whether --enable-iodebug or --disable-iodebug was given.
 if test "${enable_iodebug+set}" = set; then
@@ -4359,7 +4336,7 @@ fi
 
 
 echo $ac_n "checking for gui library to use""... $ac_c" 1>&6
-echo "configure:4363: checking for gui library to use" >&5
+echo "configure:4340: checking for gui library to use" >&5
 
 if (test "$with_x11" != yes) && \
    (test "$with_beos" != yes) && \
@@ -4532,7 +4509,7 @@ fi
 
 if test "$use_curses" = yes; then
   echo $ac_n "checking for mvaddch in -lcurses""... $ac_c" 1>&6
-echo "configure:4536: checking for mvaddch in -lcurses" >&5
+echo "configure:4513: checking for mvaddch in -lcurses" >&5
 ac_lib_var=`echo curses'_'mvaddch | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -4540,7 +4517,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lcurses  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 4544 "configure"
+#line 4521 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -4551,7 +4528,7 @@ int main() {
 mvaddch()
 ; return 0; }
 EOF
-if { (eval echo configure:4555: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:4532: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -4572,7 +4549,7 @@ else
 fi
 
   echo $ac_n "checking for mvaddch in -lncurses""... $ac_c" 1>&6
-echo "configure:4576: checking for mvaddch in -lncurses" >&5
+echo "configure:4553: checking for mvaddch in -lncurses" >&5
 ac_lib_var=`echo ncurses'_'mvaddch | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -4580,7 +4557,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lncurses  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 4584 "configure"
+#line 4561 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -4591,7 +4568,7 @@ int main() {
 mvaddch()
 ; return 0; }
 EOF
-if { (eval echo configure:4595: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:4572: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -4612,7 +4589,7 @@ else
 fi
 
   echo $ac_n "checking for mvaddch in -ltermlib""... $ac_c" 1>&6
-echo "configure:4616: checking for mvaddch in -ltermlib" >&5
+echo "configure:4593: checking for mvaddch in -ltermlib" >&5
 ac_lib_var=`echo termlib'_'mvaddch | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -4620,7 +4597,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-ltermlib  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 4624 "configure"
+#line 4601 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -4631,7 +4608,7 @@ int main() {
 mvaddch()
 ; return 0; }
 EOF
-if { (eval echo configure:4635: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:4612: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -4660,18 +4637,18 @@ fi
 if test "$with_rfb" = yes; then
   # first see if compiler takes "-pthread" argument
   echo $ac_n "checking for -pthread arg to compiler""... $ac_c" 1>&6
-echo "configure:4664: checking for -pthread arg to compiler" >&5
+echo "configure:4641: checking for -pthread arg to compiler" >&5
   CFLAGS_SAVE="$CFLAGS"
   CFLAGS="$CFLAGS -pthread"
   cat > conftest.$ac_ext <<EOF
-#line 4668 "configure"
+#line 4645 "configure"
 #include "confdefs.h"
  #include <pthread.h> 
 int main() {
  pthread_create(0,0,0,0); 
 ; return 0; }
 EOF
-if { (eval echo configure:4675: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:4652: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
    
       # it compiles with -pthread
@@ -4687,7 +4664,7 @@ else
       # now try with -lpthread
       CFLAGS="$CFLAGS_SAVE"
       echo $ac_n "checking for pthread_create in -lpthread""... $ac_c" 1>&6
-echo "configure:4691: checking for pthread_create in -lpthread" >&5
+echo "configure:4668: checking for pthread_create in -lpthread" >&5
 ac_lib_var=`echo pthread'_'pthread_create | sed 'y%./+-%__p_%'`
 if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
@@ -4695,7 +4672,7 @@ else
   ac_save_LIBS="$LIBS"
 LIBS="-lpthread  $LIBS"
 cat > conftest.$ac_ext <<EOF
-#line 4699 "configure"
+#line 4676 "configure"
 #include "confdefs.h"
 /* Override any gcc2 internal prototype to avoid an error.  */
 /* We use char because int might match the return type of a gcc2
@@ -4706,7 +4683,7 @@ int main() {
 pthread_create()
 ; return 0; }
 EOF
-if { (eval echo configure:4710: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:4687: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
   eval "ac_cv_lib_$ac_lib_var=yes"
 else
@@ -4737,8 +4714,6 @@ fi
 rm -f conftest*
 fi
 
-# this was added to make configure work in directories other than
-# the main $BOCHS dir.
 if test ! -d instrument; then
   mkdir instrument
 fi
@@ -4764,7 +4739,7 @@ fi
 # Extract the first word of "gzip", so it can be a program name with args.
 set dummy gzip; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:4768: checking for $ac_word" >&5
+echo "configure:4743: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_GZIP'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
@@ -4799,7 +4774,7 @@ fi
 # Extract the first word of "tar", so it can be a program name with args.
 set dummy tar; ac_word=$2
 echo $ac_n "checking for $ac_word""... $ac_c" 1>&6
-echo "configure:4803: checking for $ac_word" >&5
+echo "configure:4778: checking for $ac_word" >&5
 if eval "test \"`echo '$''{'ac_cv_path_TAR'+set}'`\" = set"; then
   echo $ac_n "(cached) $ac_c" 1>&6
 else
