BRANCH_PLUGINS - in the plugins branch, merge in all changes between BRANCH_PLUGINS_BASE and   BRANCH_PLUGINS_BASE2, a tag that I created today.  Of course this caused   some conflicts, which I cleaned up. - this brings the plugins branch up to date with the main trunk, so that   merging it into the main trunk should be conflict-free.
Modified Files:
    .bochsrc .conf.beos .conf.macosx Makefile.in bochs.h
    config.h.in configure configure.in gdbstub.cc main.cc
    pc_system.cc pc_system.h bios/BIOS-bochs-latest bios/rombios.c
    cpu/Makefile.in cpu/access.cc cpu/apic.cc cpu/arith16.cc
    cpu/arith32.cc cpu/arith8.cc cpu/cpu.cc cpu/cpu.h
    cpu/ctrl_xfer32.cc cpu/debugstuff.cc cpu/exception.cc
    cpu/fetchdecode.cc cpu/fetchdecode64.cc cpu/flag_ctrl.cc
    cpu/flag_ctrl_pro.cc cpu/i387.h cpu/init.cc cpu/io.cc
    cpu/logical16.cc cpu/logical32.cc cpu/logical8.cc cpu/mmx.cc
    cpu/paging.cc cpu/proc_ctrl.cc cpu/protect_ctrl.cc
    cpu/segment_ctrl_pro.cc cpu/shift16.cc cpu/shift32.cc
    cpu/stack64.cc cpu/string.cc cpu/tasking.cc debug/dbg_main.cc
    doc/docbook/user/user.dbk gui/carbon.cc gui/control.cc
    gui/gui.cc gui/keymap.cc gui/keymap.h gui/sdl.cc
    gui/siminterface.cc gui/siminterface.h gui/wx.cc
    gui/wxdialog.cc gui/wxdialog.h gui/wxmain.cc gui/wxmain.h
    gui/x.cc gui/keymaps/x11-pc-de.map
    instrument/example0/instrument.h
    instrument/example1/instrument.h
    instrument/stubs/instrument.cc instrument/stubs/instrument.h
    iodev/cdrom.cc iodev/cmos.cc iodev/devices.cc
    iodev/eth_fbsd.cc iodev/eth_linux.cc iodev/eth_null.cc
    iodev/eth_tap.cc iodev/floppy.cc iodev/harddrv.cc
    iodev/keyboard.cc iodev/ne2k.cc iodev/parallel.cc
    iodev/pit_wrap.cc iodev/sb16.cc iodev/serial.cc
    iodev/slowdown_timer.cc iodev/vga.cc iodev/vga.h
    misc/bximage.c misc/niclist.c
    patches/patch.sysenterexit-mrieker
Added Files:
    build/macosx/bochs.applescript build/macosx/script.data
    build/macosx/script.r cpu/sse.cc cpu/sse2.cc cpu/xmm.h
    gui/sdlkeys.h gui/keymaps/sdl-pc-de.map
    gui/keymaps/sdl-pc-us.map patches/patch.replace-Boolean.gz
    patches/patch.tekram-dc280e-vlb-ide
Removed Files:
    Bochs.proj.hqx patches/patch.4ata-channels
    patches/patch.apic-ppr-try patches/patch.blkdevsize
    patches/patch.eflags-bitfield patches/patch.optional-romimages
    patches/patch.programmatic-shutdown
    patches/patch.wx-raw-keycodes

diff --git a/bochs/configure.in b/bochs/configure.in
--- a/bochs/configure.in
+++ b/bochs/configure.in
@@ -2,7 +2,7 @@ dnl // Process this file with autoconf to produce a configure script.
 
 AC_PREREQ(2.50)
 AC_INIT(bochs.h)
-AC_REVISION([[$Id: configure.in,v 1.147.2.20 2002-10-23 12:49:39 bdenney Exp $]])
+AC_REVISION([[$Id: configure.in,v 1.147.2.21 2002-10-23 19:31:38 bdenney Exp $]])
 AC_CONFIG_HEADER(config.h)
 AC_CONFIG_HEADER(ltdlconf.h)
 
@@ -140,11 +140,33 @@ AC_CHECK_FUNCS(gettimeofday, AC_DEFINE(BX_HAVE_GETTIMEOFDAY))
 AC_CHECK_TYPE(socklen_t, AC_DEFINE(BX_HAVE_SOCKLEN_T), , [#include <sys/types.h>
 #include <sys/socket.h>])
 
+dnl As of autoconf 2.53, the standard largefile test fails for Linux/gcc.
+dnl It does not put the largefiles arguments into CFLAGS, even though Linux/gcc
+dnl does need them.  Since wxWindows had already solved this exact problem,
+dnl Bryce asked Vadim Zeitlin of the wxWindows project if Bochs could grab
+dnl their largefile test, and he said it was fine.  The re-implemented
+dnl AC_SYS_LARGEFILE test can be found in aclocal.m4.
 AC_SYS_LARGEFILE
-# Warning: wxwindows uses their own macro to test for largefile usability,
-# because they found bugs in the standard autoconf test that affect Linux/gcc.
-# We may need to do something similar.  See aclocal.m4 in wxWindows sources, at
-# http://cvs.wxwindows.org/cgi-bin/viewcvs.cgi/wxWindows/aclocal.m4
+
+dnl This logic came from wxWindows as well.  Bryce added the CFLAGS and 
+dnl CXXFLAGS lines, since Bochs makefiles don't use CPPFLAGS at all.
+dnl
+dnl we need to define _FILE_OFFSET_BITS or _LARGE_FILES on the compiler command
+dnl line because otherwise the system headers risk being included before
+dnl config.h which defines these constants leading to inconsistent
+dnl sizeof(off_t) in different source files of the same program and linking
+dnl problems
+if test "x$wx_largefile" = "xyes"; then
+    if test "x$ac_cv_sys_file_offset_bits" = "x64"; then
+        BX_LARGEFILE_FLAGS="-D_FILE_OFFSET_BITS=64 -D_LARGE_FILES"
+    else 
+        BX_LARGEFILE_FLAGS="-D_LARGE_FILES"
+    fi
+    CPPFLAGS="$CPPFLAGS $BX_LARGEFILE_FLAGS"
+    CFLAGS="$CFLAGS $BX_LARGEFILE_FLAGS"
+    CXXFLAGS="$CXXFLAGS $BX_LARGEFILE_FLAGS"
+fi
+dnl ---end of largefile tests
 
 AC_MSG_CHECKING(for struct timeval)
 AC_TRY_COMPILE([#include <sys/time.h>],
@@ -1281,7 +1303,44 @@ AC_ARG_ENABLE(fpu,
 AC_SUBST(FPU_VAR)
 AC_SUBST(FPU_GLUE_OBJ)
 
+support_sse=0
+AC_MSG_CHECKING(for SSE support)
+AC_ARG_ENABLE(sse,
+  [  --enable-sse                      SSE/SSE2 support (--enable-sse=[no|1|2])],
+  [case "$enableval" in
+    no | 0)
+      support_sse=0
+      AC_MSG_RESULT(no)
+      ;;
+    yes | 1)
+      support_sse=1
+      AC_MSG_RESULT(SSE only)
+      ;;
+    2)
+      support_sse=2
+      AC_MSG_RESULT(SSE and SSE2)
+      ;;
+    *)
+      echo "ERROR: --enable-sse=$enableval not understood. Use --enable-sse=[no|1|2]"
+      exit 1
+      ;;
+   esac
+   ],
+  [
+    AC_MSG_RESULT(no)
+  ]
+  )
 
+if test "$support_sse" = 2; then
+  AC_DEFINE(BX_SUPPORT_SSE,  1)
+  AC_DEFINE(BX_SUPPORT_SSE2, 1)
+elif test "$support_sse" = 1; then
+  AC_DEFINE(BX_SUPPORT_SSE,  1)
+  AC_DEFINE(BX_SUPPORT_SSE2, 0)
+else
+  AC_DEFINE(BX_SUPPORT_SSE,  0)
+  AC_DEFINE(BX_SUPPORT_SSE2, 0)
+fi
 
 AC_MSG_CHECKING(for x86 debugger support)
 AC_ARG_ENABLE(x86-debugger,
@@ -1422,7 +1481,7 @@ AC_SUBST(GDBSTUB_VAR)
 
 
 AC_ARG_ENABLE(hga-dumps,
-  [  --enable-hga-dumps=Nmicroseconds  copy memory to HGA video buffer every N useconds],
+  [  --enable-hga-dumps=Nmicroseconds  copy memory to HGA buffer every N usec],
   AC_DEFINE_UNQUOTED(BX_EMULATE_HGA_DUMPS, $enableval),
   )
 
@@ -1555,7 +1614,6 @@ fi
 AC_MSG_CHECKING(for wxWindows configuration script)
 AC_MSG_RESULT($WX_CONFIG)
   
-  AC_MSG_NOTICE([using $WX_CONFIG as wxWindows configuration script])
 ok_wx_version=0
 AC_MSG_CHECKING(for wxWindows library version)
 if test x$WX_CONFIG != xnot_found; then
