make ICACHE always enabled option and deprecate it in the configure script Trace cache still can be turned off

diff --git a/bochs/configure b/bochs/configure
--- a/bochs/configure
+++ b/bochs/configure
@@ -1569,7 +1569,6 @@ Optional Features:
   --enable-mtrr                     support for MTRRs
   --enable-repeat-speedups          support repeated IO and mem copy speedups
   --enable-trace-cache              support instruction trace cache
-  --enable-icache                   support instruction cache
   --enable-fast-function-calls      support for fast function calls (gcc on x86 only)
   --enable-host-specific-asms       support for host specific inline assembly
   --enable-configurable-msrs        support for configurable MSR registers
@@ -1613,6 +1612,7 @@ Optional Features:
   --enable-docbook                  build the Docbook documentation
   --enable-xpm                      enable the check for XPM support
   --enable-guest2host-tlb          enables guest to host addr TLB for speed (deprecated)
+  --enable-icache                   support instruction cache (deprecated)
   --enable-external-debugger       enables external debugger interface (deprecated)
   --enable-magic-breakpoints        enables magic breakpoints (deprecated)
   --enable-save-restore             enables save/restore (deprecated)
@@ -34739,29 +34739,6 @@ echo "${ECHO_T}no" >&6; }
 fi
 
 
-{ echo "$as_me:$LINENO: checking for instruction cache support" >&5
-echo $ECHO_N "checking for instruction cache support... $ECHO_C" >&6; }
-# Check whether --enable-icache was given.
-if test "${enable_icache+set}" = set; then
-  enableval=$enable_icache; if test "$enableval" = yes; then
-    { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-    speedup_iCache=1
-   else
-    { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-    speedup_iCache=0
-   fi
-else
-
-    { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-    speedup_iCache=0
-
-
-fi
-
-
 { echo "$as_me:$LINENO: checking for gcc fast function calls optimization" >&5
 echo $ECHO_N "checking for gcc fast function calls optimization... $ECHO_C" >&6; }
 # Check whether --enable-fast-function-calls was given.
@@ -35147,15 +35124,8 @@ fi
 if test "$speedups_all" = 1; then
   # Configure requested to force all options enabled.
   speedup_repeat=1
-  speedup_iCache=1
   speedup_TraceCache=1
   speedup_fastcall=1
-fi
-
-if test "$speedup_iCache" = 0 -a "$speedup_TraceCache" = 1; then
-  { { echo "$as_me:$LINENO: error: iCache is required to compile with trace cache optimization" >&5
-echo "$as_me: error: iCache is required to compile with trace cache optimization" >&2;}
-   { (exit 1); exit 1; }; }
 fi
 
 if test "$speedup_repeat" = 1; then
@@ -35166,18 +35136,6 @@ _ACEOF
 else
   cat >>confdefs.h <<\_ACEOF
 #define BX_SupportRepeatSpeedups 0
-_ACEOF
-
-fi
-
-if test "$speedup_iCache" = 1; then
-  cat >>confdefs.h <<\_ACEOF
-#define BX_SUPPORT_ICACHE 1
-_ACEOF
-
-else
-  cat >>confdefs.h <<\_ACEOF
-#define BX_SUPPORT_ICACHE 0
 _ACEOF
 
 fi
@@ -39515,6 +39473,24 @@ echo $ECHO_N "checking for guest to host TLB support (deprecated)... $ECHO_C" >&
 # Check whether --enable-guest2host-tlb was given.
 if test "${enable_guest2host_tlb+set}" = set; then
   enableval=$enable_guest2host_tlb; { echo "$as_me:$LINENO: result: $enableval" >&5
+echo "${ECHO_T}$enableval" >&6; }
+   { { echo "$as_me:$LINENO: error: DEPRECATED - ALWAYS ON" >&5
+echo "$as_me: error: DEPRECATED - ALWAYS ON" >&2;}
+   { (exit 1); exit 1; }; }
+
+else
+
+   { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+fi
+
+
+{ echo "$as_me:$LINENO: checking for instruction cache support (deprecated)" >&5
+echo $ECHO_N "checking for instruction cache support (deprecated)... $ECHO_C" >&6; }
+# Check whether --enable-icache was given.
+if test "${enable_icache+set}" = set; then
+  enableval=$enable_icache; { echo "$as_me:$LINENO: result: $enableval" >&5
 echo "${ECHO_T}$enableval" >&6; }
    { { echo "$as_me:$LINENO: error: DEPRECATED - ALWAYS ON" >&5
 echo "$as_me: error: DEPRECATED - ALWAYS ON" >&2;}
