make port_e9_hack runtime option (and not configure time) clean-up a bit in bx_dbg struct in bochs.h

diff --git a/bochs/configure b/bochs/configure
--- a/bochs/configure
+++ b/bochs/configure
@@ -1573,7 +1573,6 @@ Optional Features:
   --enable-host-specific-asms       support for host specific inline assembly
   --enable-configurable-msrs        support for configurable MSR registers
   --enable-ignore-bad-msr           ignore bad MSR references
-  --enable-port-e9-hack             writes to port e9 go to console
   --enable-show-ips                 show IPS in Bochs log file
   --enable-cpp                      use .cpp as C++ suffix
   --enable-debugger                 compile in support for Bochs internal debugger
@@ -1614,6 +1613,7 @@ Optional Features:
   --enable-guest2host-tlb           enables guest to host addr TLB for speed (deprecated)
   --enable-icache                   support instruction cache (deprecated)
   --enable-external-debugger        enables external debugger interface (deprecated)
+  --enable-port-e9-hack             writes to port e9 go to console (deprecated)
 
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
@@ -34856,38 +34856,6 @@ _ACEOF
 fi
 
 
-{ echo "$as_me:$LINENO: checking for port e9 hack" >&5
-echo $ECHO_N "checking for port e9 hack... $ECHO_C" >&6; }
-# Check whether --enable-port-e9-hack was given.
-if test "${enable_port_e9_hack+set}" = set; then
-  enableval=$enable_port_e9_hack; if test "$enableval" = yes; then
-    { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-    cat >>confdefs.h <<\_ACEOF
-#define BX_PORT_E9_HACK 1
-_ACEOF
-
-   else
-    { echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6; }
-    cat >>confdefs.h <<\_ACEOF
-#define BX_PORT_E9_HACK 0
-_ACEOF
-
-   fi
-else
-
-    { echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6; }
-    cat >>confdefs.h <<\_ACEOF
-#define BX_PORT_E9_HACK 1
-_ACEOF
-
-
-
-fi
-
-
 { echo "$as_me:$LINENO: checking show IPS" >&5
 echo $ECHO_N "checking show IPS... $ECHO_C" >&6; }
 # Check whether --enable-show-ips was given.
@@ -39526,6 +39494,25 @@ else
 echo "${ECHO_T}no" >&6; }
 
 fi
+
+
+{ echo "$as_me:$LINENO: checking writes to port e9 go to console (deprecated)" >&5
+echo $ECHO_N "checking writes to port e9 go to console (deprecated)... $ECHO_C" >&6; }
+# Check whether --enable-port-e9-hack was given.
+if test "${enable_port_e9_hack+set}" = set; then
+  enableval=$enable_port_e9_hack; { echo "$as_me:$LINENO: result: $enableval" >&5
+echo "${ECHO_T}$enableval" >&6; }
+   { { echo "$as_me:$LINENO: error: DEPRECATED - PORT_E9_HACK could be configured through .bochsrc" >&5
+echo "$as_me: error: DEPRECATED - PORT_E9_HACK could be configured through .bochsrc" >&2;}
+   { (exit 1); exit 1; }; }
+
+else
+
+   { echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6; }
+
+fi
+
 
 
 # Create some subdirectories for when you run configure from some other
