Added some preliminary configure and config.h stuff for   SSE/SSE2 for Stanislav.  Also, some method prototypes and   skeletal functions in access.cc for read/write double quadword   features.
Also cleaned up one warning in protect_ctrl.cc for non-64 bit compiles.
  There was an unused variable, only used for 64-bit.

diff --git a/bochs/configure b/bochs/configure
--- a/bochs/configure
+++ b/bochs/configure
@@ -878,6 +878,7 @@ Optional Features:
   --enable-vbe                      use VESA BIOS extensions
   --enable-mmx                      compile in MMX emulation
   --enable-fpu                      compile in FPU emulation
+  --enable-sse                      =1 (SSE) =2 (SSE2) support
   --enable-x86-debugger             x86 debugger support
   --enable-cdrom                    CDROM support
   --enable-sb16=xxx                 Sound Blaster 16 Support (xxx=dummy|win|linux|freebsd)
@@ -10361,7 +10362,70 @@ fi;
 
 
 
+support_sse=0
+echo "$as_me:$LINENO: checking for SSE support" >&5
+echo $ECHO_N "checking for SSE support... $ECHO_C" >&6
+# Check whether --enable-sse or --disable-sse was given.
+if test "${enable_sse+set}" = set; then
+  enableval="$enable_sse"
+  case "$enableval" in
+    no | 0)
+      support_sse=0
+      echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+      ;;
+    yes | 1)
+      support_sse=1
+      echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+      ;;
+    2)
+      support_sse=2
+      echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+      ;;
+    *)
+      echo "ERROR: --enable-sse=$enableval not understood"
+      exit 1
+      ;;
+   esac
 
+else
+
+    echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
+
+fi;
+
+if test "$support_sse" = 2; then
+  cat >>confdefs.h <<\_ACEOF
+#define BX_SUPPORT_SSE 1
+_ACEOF
+
+  cat >>confdefs.h <<\_ACEOF
+#define BX_SUPPORT_SSE2 1
+_ACEOF
+
+elif test "$support_sse" = 1; then
+  cat >>confdefs.h <<\_ACEOF
+#define BX_SUPPORT_SSE 1
+_ACEOF
+
+  cat >>confdefs.h <<\_ACEOF
+#define BX_SUPPORT_SSE2 0
+_ACEOF
+
+else
+  cat >>confdefs.h <<\_ACEOF
+#define BX_SUPPORT_SSE 0
+_ACEOF
+
+  cat >>confdefs.h <<\_ACEOF
+#define BX_SUPPORT_SSE2 0
+_ACEOF
+
+fi
 
 echo "$as_me:$LINENO: checking for x86 debugger support" >&5
 echo $ECHO_N "checking for x86 debugger support... $ECHO_C" >&6
diff --git a/bochs/configure.in b/bochs/configure.in
--- a/bochs/configure.in
+++ b/bochs/configure.in
@@ -2,7 +2,7 @@ dnl // Process this file with autoconf to produce a configure script.
 
 AC_PREREQ(2.50)
 AC_INIT(bochs.h)
-AC_REVISION([[$Id: configure.in,v 1.148 2002-10-05 12:07:51 bdenney Exp $]])
+AC_REVISION([[$Id: configure.in,v 1.149 2002-10-11 01:11:10 kevinlawton Exp $]])
 AC_CONFIG_HEADER(config.h)
 
 dnl // Put Bochs version information right here so that it gets substituted
@@ -1126,7 +1126,44 @@ AC_ARG_ENABLE(fpu,
 AC_SUBST(FPU_VAR)
 AC_SUBST(FPU_GLUE_OBJ)
 
+support_sse=0
+AC_MSG_CHECKING(for SSE support)
+AC_ARG_ENABLE(sse,
+  [  --enable-sse                      =1 (SSE) =2 (SSE2) support],
+  [case "$enableval" in
+    no | 0)
+      support_sse=0
+      AC_MSG_RESULT(no)
+      ;;
+    yes | 1)
+      support_sse=1
+      AC_MSG_RESULT(yes)
+      ;;
+    2)
+      support_sse=2
+      AC_MSG_RESULT(yes)
+      ;;
+    *)
+      echo "ERROR: --enable-sse=$enableval not understood"
+      exit 1
+      ;;
+   esac
+   ],
+  [
+    AC_MSG_RESULT(no)
+  ]
+  )
 
+if test "$support_sse" = 2; then
+  AC_DEFINE(BX_SUPPORT_SSE,  1)
+  AC_DEFINE(BX_SUPPORT_SSE2, 1)
+elif test "$support_sse" = 1; then
+  AC_DEFINE(BX_SUPPORT_SSE,  1)
+  AC_DEFINE(BX_SUPPORT_SSE2, 0)
+else
+  AC_DEFINE(BX_SUPPORT_SSE,  0)
+  AC_DEFINE(BX_SUPPORT_SSE2, 0)
+fi
 
 AC_MSG_CHECKING(for x86 debugger support)
 AC_ARG_ENABLE(x86-debugger,
